function Sd(){}
function Hd(a){this.b=a}
function Kd(a){this.b=a}
function Nd(a){this.b=a}
function Ud(){Ud=Btc;Pd=new Sd}
function Qkc(a){!a.g&&(a.g=new Fd);return a.g}
function Dd(){Dd=Btc;Cd=(H5(),u5(wJ.i));L5(Cd,Cwc);Rd((Ud(),Pd));L5(Cd,Dwc)}
function Rd(a){if(!a.b){a.b=true;Yy();qp(Vy,'.GH-1-SCCI{position:absolute;top:0;bottom:0;height:100%;width:0;background-color:white;}');az();return true}return false}
function Ed(a){var b,c,d;c=new hbc;for(b=0;b<a.length;++b){d=a[b];fbc(c,'{touch-id:'+d.identifier);fbc(c,';touch-pageX:'+d.pageX);fbc(c,';touch-pageY:'+d.pageY);fbc(c,';touch-clientX:'+d.clientX);fbc(c,';touch-clientY:'+d.clientY);fbc(c,';touch-screenX:'+d.screenX);fbc(c,';touch-screenY:'+d.screenY);c.b.b+=Gxc}M5(Cd,c.b.b)}
function Fd(){Dd();var a,b;vd.call(this);a=new Ulb('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla at turpis eget nibh ultricies dignissim. Duis luctus euismod turpis. Mauris augue. Aliquam facilisis semper elit. Pellentesque semper hendrerit arcu. Phasellus eleifend commodo justo. Aliquam orci urna, imperdiet sit amet, posuere in, lobortis et, risus. Integer interdum nonummy erat. Nullam tellus. Sed accumsan. Vestibulum orci ipsum, eleifend vitae, mollis vel, mollis sed, purus. Suspendisse mollis elit eu magna. Morbi egestas. Nunc leo ipsum, blandit ac, viverra quis, porttitor quis, dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus scelerisque ipsum ut justo. Pellentesque et ligula eu massa sagittis rutrum. In urna nibh, eleifend vel, suscipit ut, sagittis id, nunc.Nam ut sapien sed pede pulvinar rutrum. Nunc eu elit sed augue aliquet tincidunt. Morbi rutrum. Vestibulum dui turpis, lobortis quis, euismod sed, consectetuer sit amet, nunc. Nam mi. Fusce at nisl eu tortor bibendum eleifend. Sed ac metus. Phasellus nec elit. Morbi tortor nulla, tristique a, adipiscing at, consectetuer et, nisi. Nunc vel sapien sed risus hendrerit egestas. Vivamus turpis arcu, placerat eu, congue vel, commodo ut, nisl.&lt;');a.X.style[zDc]='100px';a.X.style[_vc]=bEc;a.X.style[Yvc]='700px';b=new Ulb(Zvc);$(b,(Ud(),'GH-1-SCCI'));dd(a,b,a.X);ud(this,a);qb(a,new Hd(this),(BC(),BC(),AC));qb(a,new Kd(this),(vC(),vC(),uC));qb(a,new Nd(this),(nC(),nC(),mC))}
Y3(40,35,Itc,Fd);_.b=false;_.c=false;_.d=0;_.e=0;var Cd;Y3(41,1,Ktc,Hd);_.Bb=function Id(a){var b;b=a.b.touches;switch(b.length){case 1:M5((Dd(),Cd),ADc);this.b.c=false;break;case 2:M5((Dd(),Cd),BDc);this.b.c=false;}};_.b=null;Y3(42,1,Ltc,Kd);_.Cb=function Ld(a){var b,c,d,e,f,g,i;a.b.preventDefault();i=a.b.touches;switch(i.length){case 1:if(this.b.b){return}this.b.b=true;Ed(i);break;case 2:if(this.b.c){return}this.b.c=true;f=i[0];g=i[1];b=f.pageX;c=g.pageX;d=b-this.b.d;e=c-this.b.e;if(d>0&&e>0){return}else if(d<0&&e<0){return}Ed(i);}};_.b=null;Y3(43,1,Mtc,Nd);_.Db=function Od(a){this.b.b=false;this.b.c=false};_.b=null;var Pd=null;Y3(45,1,{},Sd);_.sb=function Td(){return Rd(this)};_.b=false;Y3(1347,1,Uvc);_.Pc=function goc(){Apc(this.c,Qkc(this.b.b))};var sJ=a9b(mBc,'WaveTest$1',41,H$),tJ=a9b(mBc,'WaveTest$2',42,H$),uJ=a9b(mBc,'WaveTest$3',43,H$),vJ=a9b(mBc,'WaveTest_Bundle_zh_InlineClientBundleGenerator$1',45,H$);Wvc(Pp)(22);