function $i(){}
function bj(){}
function hj(){}
function KVb(){}
function NVb(){}
function GVb(a){this.b=a}
function Noc(a){this.b=a}
function qwb(a){a.g=0;return a}
function p2(a,b){Jdc(a.b,b);return a}
function ej(){ej=Nwc;Zi=new bj}
function PVb(){PVb=Nwc;JVb=new NVb}
function nk(){ok.call(this,new qk)}
function swb(){twb.call(this,qwb(new nk))}
function twb(a){kbb.call(this,a);this.b=a}
function Vi(a){this.b=a;this.c=Xfb(this)}
function Si(){Ti.call(this,!Pi&&(Pi=new $i))}
function qk(){Si.call(this,!Z2&&(Z2=new _2))}
function pwb(a){if(a.b.d==2){return}a.b.d=2;hbb(a)}
function zVb(a){var b;b=Vmc(a.d.b);bsc(b,kT.i);m1(a.b,b)}
function yVb(a){var b;b=cnc(a.c.b);Ogc(a.e,b);return b}
function ok(a){yi.call(this,rD(qZ,Xwc,1,[iBc,lBc,pBc]));this.c=a}
function AVb(a,b,c){this.e=new Ygc;this.c=a;this.b=b;this.d=c;Qc(this,DVb(new EVb(this)))}
function Ti(){this.b=(RA(),tzc);this.c=(C2(),x2);this.d=(ej(),Zi);aj(this.d);!Qi&&(Qi=new hj)}
function Pmc(a){var b;b=new AVb(new Noc(a),(!a.e&&(a.e=xnc(new ysc,(!a.j&&(a.j=new Rx),a.j))),a.e),new dqc(a));return b}
function MVb(a){if(!a.b){a.b=true;ft((RA(),'.GHVL5HDCHK{width:100%;background:black;}.GHVL5HDCHK .GHVL5HDCGK{float:left;color:white;width:100%;}'));return true}return false}
function dj(){dj=Nwc;Yi=new $1((J2(),new G2((RA(),'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAfCAYAAACGVs+MAAAAL0lEQVR42u3OMQ0AAAzDsPJnWwQbjD6OlN+5cWl7ywEAAAAAAAAAAAAAAAAA5oAHQZjT082H5T4AAAAASUVORK5CYII='))),32,31)}
function gj(a,b,c,d){var e;e=new Pdc;e.b.b+='<div class="';Jdc(e,D2(a));e.b.b+='" style="position:relative;padding-';Jdc(e,D2(b));e.b.b+=Szc;Jdc(e,D2('3'));e.b.b+='px;zoom:0;">';Jdc(e,c.b);Jdc(e,d.b);e.b.b+=RFc;return new j2(e.b.b)}
function EVb(a){this.o=new GVb(this);this.p=a;this.q=(new KVb,PVb(),JVb);MVb(this.q);this.b=cq($doc);this.d=cq($doc);this.f=cq($doc);this.i=cq($doc);this.k=cq($doc);this.c=new u4(this.b);this.e=new u4(this.d);this.g=new u4(this.f);this.j=new u4(this.i);this.n=new u4(this.k)}
function QVb(a,b,c,d,e){var f;f=new Pdc;f.b.b+="<table cellpadding='0' cellspacing='2' class='";Jdc(f,D2(cGc));f.b.b+="'> <tr> <td align='center' style='width:20%;'> <span id='";Jdc(f,D2(a));f.b.b+=eGc;Jdc(f,D2(b));f.b.b+=eGc;Jdc(f,D2(c));f.b.b+=eGc;Jdc(f,D2(d));f.b.b+=eGc;Jdc(f,D2(e));f.b.b+="'><\/span> <\/td> <\/tr> <\/table>";return new j2(f.b.b)}
function Ri(a,b,c,d){var e,f,g,i,j,k,n,o;g=new q2;Jdc(g.b,D2('GHVL5HDCE'));j=b.d;j==1?(Jdc(g.b,D2(' GHVL5HDCJ')),g):j==2?(Jdc(g.b,D2(' GHVL5HDCI')),g):(Jdc(g.b,D2(' GHVL5HDCH')),g);b.e&&(Jdc(g.b,D2(' GHVL5HDCF')),g);b.f&&(Jdc(g.b,D2(' GHVL5HDCG')),g);e=b.b;f=new Pdc;if(e!=0){Jdc((f.b.b+='accessKey="',f),D2(jzc+String.fromCharCode(e)));f.b.b+=bGc}n=$2(AD(c,1));i=gj(Q1(),a.b,a.c,n);o=b.g;k=new Pdc;k.b.b+='<button type="button"';Jdc(k,' class="'+(new s2(g.b.b.b)).b+Fzc);xn(k.b,' tabindex="'+o+bGc);Jdc(Jdc(k,f.b.b),NAc);p2(d,k.b.b);Jdc(d.b,i.b);Jdc(d.b,'<\/button>')}
function DVb(a){var b,c,d,e,f,g,i,j;b=new Ckb((ns(),ms));skb(b,(c=new nmb(QVb(a.b,a.d,a.f,a.i,a.k).b),c._[zzc]=cGc,d=w4(c._),t4(a.c),t4(a.e),t4(a.g),t4(a.j),t4(a.n),d.c?vp(d.c,d.b,d.d):z4(d.b),kmb(c,(e=new swb,ibb(e,'\u6700\u65B0',false,true),e._[zzc]=dGc,e),t4(a.c)),kmb(c,(f=new swb,ibb(f,'\u6392\u884C',false,true),f._[zzc]=dGc,f),t4(a.e)),kmb(c,(g=new swb,ibb(g,'\u5206\u7C7B',false,true),g._[zzc]=dGc,g),t4(a.g)),kmb(c,(i=new swb,ibb(i,'\u4E0B\u8F7D',false,true),i._[zzc]=dGc,i),t4(a.j)),kmb(c,(j=new swb,ibb(j,'\u4E0A\u4F20',false,true),j._[zzc]=dGc,pwb(j),Yb(j,a.o,(Jv(),Jv(),Iv)),j),t4(a.n)),c),40);b.Re(yVb(a.p),(Rkb(),Kkb),0,null);return b}
function aj(a){if(!a.b){a.b=true;ft((RA(),'.GHVL5HDCE{height:'+(dj(),Yi.b)+wCc+Yi.e.b+xCc+Yi.c+yCc+Yi.d+'px  repeat-x;height:auto;background-color:#f1f1f1;margin:0;padding:5px 7px;text-decoration:none;cursor:pointer;cursor:hand;font-size:small;border:1px solid #bbb;border-bottom:1px solid #a0a0a0;border-radius:5px;-moz-border-radius:5px;}.GHVL5HDCJ{background:#666;color:white;}.GHVL5HDCI{background:#940000;color:white;}.GHVL5HDCE:hover{border-color:#939393;}.GHVL5HDCE[disabled]{cursor:default;color:#888;}.GHVL5HDCE[disabled]:hover{border-color:#bbb #bbb #a0a0a0;}.GHVL5HDCK{border:1px inset #ccc;}.GHVL5HDCF{border-top-left-radius:0;border-bottom-left-radius:0;-moz-border-radius-topleft:0;-moz-border-radius-bottomleft:0;}.GHVL5HDCG{border-right:none;border-top-right-radius:0;border-bottom-right-radius:0;-moz-border-radius-topright:0;-moz-border-radius-bottomright:0;}'));return true}return false}
var bGc='" ',eGc="'><\/span> <\/td> <td align='center' style='width:20%;'> <span id='",dGc='GHVL5HDCGK',cGc='GHVL5HDCHK',aGc='GHVL5HDCK',fGc='com.google.gwt.widget.client.';s$(99,96,{});_.uc=function Li(a,b,c,d,e){var f,g;wi(this,a,b,c,d,e);g=d.target;if(!Yp(Mp(b),g)){return}f=d.type;if(Pcc(iBc,f)){!!e&&e.Bc(c)}else if(Pcc(pBc,f)){Ap(Mp(b),aGc);new Vi(b);d.preventDefault()}};_.vc=function Mi(a,b,c,d,e){!!e&&e.Bc(c)};_.wc=function Ni(a,b,c){Ri(this.c,this,b,c)};_.b=0;_.c=null;_.d=0;_.e=false;_.f=false;_.g=-1;s$(100,1,{});_.d=null;var Pi=null,Qi=null;s$(101,1,ixc,Vi);_.yc=function Wi(a){if(Pcc(tBc,a.e.type)){rDb(this.c.b);Dp(Mp(this.b),aGc)}};_.b=null;_.c=null;s$(102,1,{},$i);var Yi=null,Zi=null;s$(103,1,{},bj);_.hb=function cj(){return aj(this)};_.b=false;s$(106,1,{},hj);s$(115,99,{},nk);s$(116,100,{},qk);s$(723,495,Swc);_.b=null;s$(724,723,Swc,swb);s$(943,15,_wc,AVb);_.Gb=function BVb(a){var b,c;for(c=new Zfc(this.e);c.c<c.e.tf();){b=AD(Xfc(c),104);DD(b,211)&&AD(b,211).Gb(a)}};_.b=null;_.c=null;_.d=null;s$(944,1,{},EVb);_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;_.k=null;_.n=null;_.p=null;_.q=null;s$(945,1,Ywc,GVb);_.Lb=function HVb(a){zVb(this.b.p)};_.b=null;s$(946,1,{},KVb);var JVb=null;s$(947,1,{},NVb);_.hb=function OVb(){return MVb(this)};_.b=false;s$(1219,1,Rwc,Noc);_.ab=function Moc(){return cnc(this.b)};_.b=null;s$(1221,1,azc);_.Gc=function Toc(){Mrc(this.c,Pmc(this.b.b))};var NW=pbc(bEc,'org_cloudlet_web_boot_client_BootInjectorImpl$15',1219,bV),ZR=pbc(rEc,'HomeView',943,zL),WR=pbc(rEc,'HomeView_BinderImpl$Widgets',944,bV),VR=pbc(rEc,'HomeView_BinderImpl$Widgets$1',945,bV),hO=pbc(fGc,gGc,723,tK),iO=pbc(fGc,'TextButton',724,hO),RE=pbc(hGc,'ButtonCellBase',99,JE),ME=pbc(hGc,'ButtonCellBase$DefaultAppearance',100,bV),NE=pbc(hGc,'ButtonCellBase$UnpushHandler',101,bV),YR=pbc(rEc,'HomeView_BinderImpl_GenBundle_zh_InlineClientBundleGenerator',946,bV),XR=pbc(rEc,'HomeView_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',947,bV),$E=pbc(hGc,'TextButtonCell',115,RE),ZE=pbc(hGc,'TextButtonCell$DefaultAppearance',116,ME),PE=pbc(hGc,'ButtonCellBase_DefaultAppearance_Resources_zh_InlineClientBundleGenerator',102,bV),OE=pbc(hGc,'ButtonCellBase_DefaultAppearance_Resources_zh_InlineClientBundleGenerator$1',103,bV),QE=pbc(hGc,'ButtonCellBase_DefaultAppearance_TemplateImpl',106,bV);dzc(Il)(10);