function gj(){}
function jj(){}
function pj(){}
function hXb(){}
function kXb(){}
function dXb(a){this.b=a}
function Rpc(a){this.b=a}
function Hxb(a){a.g=0;return a}
function X3(a,b){qfc(a.b,b);return a}
function mj(){mj=uyc;fj=new jj}
function mXb(){mXb=uyc;gXb=new kXb}
function vk(){wk.call(this,new yk)}
function Jxb(){Kxb.call(this,Hxb(new vk))}
function Kxb(a){Scb.call(this,a);this.b=a}
function bj(a){this.b=a;this.c=Dhb(this)}
function $i(){_i.call(this,!Xi&&(Xi=new gj))}
function yk(){$i.call(this,!F4&&(F4=new H4))}
function Gxb(a){if(a.b.d==2){return}a.b.d=2;Pcb(a)}
function YWb(a){var b;b=Coc(a.d.b);Ktc(b,TU.i);U2(a.b,b)}
function XWb(a){var b;b=Loc(a.c.b);vic(a.e,b);return b}
function wk(a){Gi.call(this,DE(Z$,Dyc,1,[FCc,ICc,MCc]));this.c=a}
function ZWb(a,b,c){this.e=new Fic;this.c=a;this.b=b;this.d=c;Ic(this,aXb(new bXb(this)))}
function _i(){this.b=(bC(),_Ac);this.c=(i4(),d4);this.d=(mj(),fj);ij(this.d);!Yi&&(Yi=new pj)}
function woc(a){var b;b=new ZWb(new Rpc(a),(!a.e&&(a.e=epc(new fuc,(!a.j&&(a.j=new bz),a.j))),a.e),new Opc(a));return b}
function jXb(a){if(!a.b){a.b=true;ru((bC(),'.GKI3MMYGM{width:100%;background:black;}.GKI3MMYGM .GKI3MMYFM{float:left;color:white;width:100%;}'));return true}return false}
function lj(){lj=uyc;ej=new G3((p4(),new m4((bC(),'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAfCAYAAACGVs+MAAAAL0lEQVR42u3OMQ0AAAzDsPJnWwQbjD6OlN+5cWl7ywEAAAAAAAAAAAAAAAAA5oAHQZjT082H5T4AAAAASUVORK5CYII='))),32,31)}
function oj(a,b,c,d){var e;e=new wfc;e.b.b+='<div class="';qfc(e,j4(a));e.b.b+='" style="position:relative;padding-';qfc(e,j4(b));e.b.b+=zBc;qfc(e,j4('3'));e.b.b+='px;zoom:0;">';qfc(e,c.b);qfc(e,d.b);e.b.b+=dHc;return new R3(e.b.b)}
function bXb(a){this.o=new dXb(this);this.p=a;this.q=(new hXb,mXb(),gXb);jXb(this.q);this.b=kq($doc);this.d=kq($doc);this.f=kq($doc);this.i=kq($doc);this.k=kq($doc);this.c=new a6(this.b);this.e=new a6(this.d);this.g=new a6(this.f);this.j=new a6(this.i);this.n=new a6(this.k)}
function nXb(a,b,c,d,e){var f;f=new wfc;f.b.b+="<table cellpadding='0' cellspacing='2' class='";qfc(f,j4(qHc));f.b.b+="'> <tr> <td align='center' style='width:20%;'> <span id='";qfc(f,j4(a));f.b.b+=tHc;qfc(f,j4(b));f.b.b+=tHc;qfc(f,j4(c));f.b.b+=tHc;qfc(f,j4(d));f.b.b+=tHc;qfc(f,j4(e));f.b.b+="'><\/span> <\/td> <\/tr> <\/table>";return new R3(f.b.b)}
function Zi(a,b,c,d){var e,f,g,i,j,k,n,o;g=new Y3;qfc(g.b,j4('GKI3MMYF'));j=b.d;j==1?(qfc(g.b,j4(' GKI3MMYK')),g):j==2?(qfc(g.b,j4(' GKI3MMYJ')),g):(qfc(g.b,j4(' GKI3MMYI')),g);b.e&&(qfc(g.b,j4(' GKI3MMYG')),g);b.f&&(qfc(g.b,j4(' GKI3MMYH')),g);e=b.b;f=new wfc;if(e!=0){qfc((f.b.b+='accessKey="',f),j4(TAc+String.fromCharCode(e)));f.b.b+=pHc}n=G4(ME(c,1));i=oj(w3(),a.b,a.c,n);o=b.g;k=new wfc;k.b.b+='<button type="button"';qfc(k,' class="'+(new $3(g.b.b.b)).b+mBc);Fn(k.b,' tabindex="'+o+pHc);qfc(qfc(k,f.b.b),iCc);X3(d,k.b.b);qfc(d.b,i.b);qfc(d.b,'<\/button>')}
function aXb(a){var b,c,d,e,f,g,i,j;b=new imb((zt(),yt));$lb(b,(c=new Snb(nXb(a.b,a.d,a.f,a.i,a.k).b),c._[gBc]=qHc,d=c6(c._),_5(a.c),_5(a.e),_5(a.g),_5(a.j),_5(a.n),d.c?Dp(d.c,d.b,d.d):f6(d.b),Pnb(c,(e=new Jxb,Qcb(e,'\u6700\u65B0',false,true),e._[gBc]=rHc,e),_5(a.c)),Pnb(c,(f=new Jxb,Qcb(f,'\u6392\u884C',false,true),f._[gBc]=rHc,f),_5(a.e)),Pnb(c,(g=new Jxb,Qcb(g,'\u5206\u7C7B',false,true),g._[gBc]=rHc,g),_5(a.g)),Pnb(c,(i=new Jxb,Qcb(i,sHc,false,true),i._[gBc]=rHc,i),_5(a.j)),Pnb(c,(j=new Jxb,Qcb(j,'\u4E0A\u4F20',false,true),j._[gBc]=rHc,Gxb(j),Xb(j,a.o,(Vw(),Vw(),Uw)),j),_5(a.n)),c),40);b.Re(XWb(a.p),(xmb(),qmb),0,null);return b}
function ij(a){if(!a.b){a.b=true;ru((bC(),'.GKI3MMYF{height:'+(lj(),ej.b)+XDc+ej.e.b+YDc+ej.c+ZDc+ej.d+'px  repeat-x;height:auto;background-color:#f1f1f1;margin:0;padding:5px 7px;text-decoration:none;cursor:pointer;cursor:hand;font-size:small;border:1px solid #bbb;border-bottom:1px solid #a0a0a0;border-radius:5px;-moz-border-radius:5px;}.GKI3MMYK{background:#666;color:white;}.GKI3MMYJ{background:#940000;color:white;}.GKI3MMYF:hover{border-color:#939393;}.GKI3MMYF[disabled]{cursor:default;color:#888;}.GKI3MMYF[disabled]:hover{border-color:#bbb #bbb #a0a0a0;}.GKI3MMYL{border:1px inset #ccc;}.GKI3MMYG{border-top-left-radius:0;border-bottom-left-radius:0;-moz-border-radius-topleft:0;-moz-border-radius-bottomleft:0;}.GKI3MMYH{border-right:none;border-top-right-radius:0;border-bottom-right-radius:0;-moz-border-radius-topright:0;-moz-border-radius-bottomright:0;}'));return true}return false}
var pHc='" ',tHc="'><\/span> <\/td> <td align='center' style='width:20%;'> <span id='",rHc='GKI3MMYFM',qHc='GKI3MMYGM',oHc='GKI3MMYL',uHc='com.google.gwt.widget.client.';__(102,99,{});_.tc=function Ti(a,b,c,d,e){var f,g;Ei(this,a,b,c,d,e);g=d.target;if(!eq(Up(b),g)){return}f=d.type;if(wec(FCc,f)){!!e&&e.Ac(c)}else if(wec(MCc,f)){Ip(Up(b),oHc);new bj(b);d.preventDefault()}};_.uc=function Ui(a,b,c,d,e){!!e&&e.Ac(c)};_.vc=function Vi(a,b,c){Zi(this.c,this,b,c)};_.b=0;_.c=null;_.d=0;_.e=false;_.f=false;_.g=-1;__(103,1,{});_.d=null;var Xi=null,Yi=null;__(104,1,Qyc,bj);_.xc=function cj(a){if(wec(QCc,a.e.type)){IEb(this.c.b);Lp(Up(this.b),oHc)}};_.b=null;_.c=null;__(105,1,{},gj);var ej=null,fj=null;__(106,1,{},jj);_.hb=function kj(){return ij(this)};_.b=false;__(109,1,{},pj);__(118,102,{},vk);__(119,103,{},yk);__(741,517,zyc);_.b=null;__(742,741,zyc,Jxb);__(967,15,Hyc,ZWb);_.Fb=function $Wb(a){var b,c;for(c=new Ghc(this.e);c.c<c.e.tf();){b=ME(Ehc(c),103);PE(b,210)&&ME(b,210).Fb(a)}};_.b=null;_.c=null;_.d=null;__(968,1,{},bXb);_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;_.k=null;_.n=null;_.p=null;_.q=null;__(969,1,Eyc,dXb);_.Kb=function eXb(a){YWb(this.b.p)};_.b=null;__(970,1,{},hXb);var gXb=null;__(971,1,{},kXb);_.hb=function lXb(){return jXb(this)};_.b=false;__(1240,1,yyc,Rpc);_.ab=function Qpc(){return Loc(this.b)};_.b=null;__(1242,1,KAc);_.Fc=function Xpc(){ttc(this.c,woc(this.b.b))};var lY=Ycc(BFc,'org_cloudlet_web_boot_client_BootInjectorImpl$10',1240,KW),ET=Ycc(HFc,'HomeView',967,jN),BT=Ycc(HFc,'HomeView_BinderImpl$Widgets',968,KW),AT=Ycc(HFc,'HomeView_BinderImpl$Widgets$1',969,KW),NP=Ycc(uHc,vHc,741,cM),OP=Ycc(uHc,'TextButton',742,NP),hG=Ycc(wHc,'ButtonCellBase',102,_F),cG=Ycc(wHc,'ButtonCellBase$DefaultAppearance',103,KW),dG=Ycc(wHc,'ButtonCellBase$UnpushHandler',104,KW),DT=Ycc(HFc,'HomeView_BinderImpl_GenBundle_zh_InlineClientBundleGenerator',970,KW),CT=Ycc(HFc,'HomeView_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',971,KW),qG=Ycc(wHc,'TextButtonCell',118,hG),pG=Ycc(wHc,'TextButtonCell$DefaultAppearance',119,cG),fG=Ycc(wHc,'ButtonCellBase_DefaultAppearance_Resources_zh_InlineClientBundleGenerator',105,KW),eG=Ycc(wHc,'ButtonCellBase_DefaultAppearance_Resources_zh_InlineClientBundleGenerator$1',106,KW),gG=Ycc(wHc,'ButtonCellBase_DefaultAppearance_TemplateImpl',109,KW);NAc(Ql)(7);