function mMb(){}
function qMb(){}
function Q5(){M5()}
function u5(a,b){a5(a.b,b)}
function wLb(a){this.b=a}
function _Lb(a){this.c=a}
function cMb(a){this.c=a}
function TLb(a,b){this.b=a;this.c=b}
function XLb(a,b){FLb();this.b=a;this.c=b}
function sMb(){sMb=gtc;iMb=new mMb}
function tMb(){tMb=gtc;jMb=new qMb}
function G5(){G5=gtc;F5=new jDb}
function P5(){P5=gtc;M5();H5(new Q5)}
function H5(a){G5();F5.Df(nP,a)}
function I5(a){G5();return N5(EI(F5.Cf(a),64))}
function mjc(a,b,c,d){return new qLb(a,b,c,d)}
function nLb(a,b,c,d){HLb(MLb(new PLb(a,b,c,d),b.Rf(),SY.i))}
function a5(a,b){i5(a,(kic(),cic),b,null)}
function jLb(){jLb=gtc;iLb=(s5(),f5(XV.i))}
function gMb(){var a;a=(tMb(),jMb);pMb(a);return a}
function pLb(a){var b;b=new $1b(a.e);HLb(KLb(new XLb(a,b),'issue.all'))}
function PLb(a,b,c,d){FLb();this.b=a;this.e=b;this.c=c;this.d=d}
function hMb(a){var b;this.d=a;b=(sMb(),iMb);lMb(b);gMb();this.b=Yt($doc);this.c=new B9(this.b)}
function uMb(a){var b;b=new cbc;b.b.b+=jwc;abc(b,I7(a));b.b.b+=kwc;return new n7(b.b.b)}
function vMb(a,b){var c;c=new cbc;c.b.b+=_Cc;abc(c,I7(a.b));c.b.b+="\" width='100%' ><div>";abc(c,I7(b));c.b.b+=eCc;return new n7(c.b.b)}
function mLb(a){var b,c;for(b=0;b<7;++b){c=lLb(i3(b),a.i);nLb(a,EI(a.j.Je(c),154),b,false)}}
function kLb(a){var b;b=$t($doc);$t($doc)>=1024?Ub(a.c,Hvc+b*0.33*2+swc):Ub(a.c,Hvc+b*0.33*2+swc)}
function WLb(a,b){a.b.j=b;a.b.i==0&&(a.b.i=a.b.j.Re());mLb(a.b);Gq((tq(),new _Lb(a)),5000);gc(a.b.b,new cMb(a),(qB(),qB(),pB))}
function lLb(a,b){return k3(a,Ytc)?x3(n3(a,i3(b))):x3(l3(n3(d3(a,i3(b)),i3(b)),Ytc)?p3(n3(d3(a,i3(b)),i3(b))):n3(d3(a,i3(b)),i3(b)))}
function M5(){M5=gtc;K5=$doc.createElement(EEc);L5=new jDb;L5.Df(FEc,GEc);L5.Df(Hxc,GEc);L5.Df('submit',HEc);L5.Df('reset',HEc);L5.Df(Vxc,IEc);L5.Df(Oxc,IEc);L5.Df('abort',IEc)}
function OLb(a,b){var c,d;d=vMb((jLb(),N7(),new K7(VCc+b.yh().c+WCc+b.wh())),a.e.ih());c=nt(a.b.b.X,a.c*2);At(c,d.b);a.d?yt(c,EI(a.b.d.Cf(v9b(3)),1)):yt(c,EI(a.b.d.Cf(v9b(a.c-3)),1));xjb(c,1);kjb(c,new TLb(a,a.e));kLb(a.b)}
function Akc(a){!a.v&&(a.v=mjc((!a.O&&(a.O=(!a.N&&(a.N=Qjc(new MOb,(!a.q&&(a.q=new pD),a.q),(!a.u&&(a.u=(!a.X&&(a.X=tkc(a)),a.X)),a.u))),a.N)),a.O),new Imc(a),(!a.$&&(a.$=wkc(a)),a.$),(!a.k&&(a.k=Zkc(new Spc,(!a.q&&(a.q=new pD),a.q))),a.k)));return a.v}
function fMb(a){var b,c,d,e;c=new Clb(uMb(a.b).b);b=D9(c.X);A9(a.c);b.c?ot(b.c,b.b,b.d):G9(b.b);zlb(c,(d=new Clb((e=new cbc,e.b.b+='<div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div>',new n7(e.b.b)).b),Vb(d,Hvc+(gMb(),'GNLEBM-BIM')+Hvc),a.d.b=d,d),A9(a.c));a.d.c=c;return c}
function N5(a){var b,c,d,e,f;!a.b&&(a.b=(h8b(),(b=(M5(),K5).style['perspectiveProperty']!==undefined||K5.style['WebkitPerspective']!==undefined,b&&(b=(c=$doc.createElement(Zwc),d=$doc.createElement(ewc),c['textContent']='@media (-webkit-transform-3d),(modernizr){#modernizr{height:3px}}',e=$doc.getElementsByTagName($wc)[0],e.appendChild(c),d.id=EEc,mt($doc.documentElement,d),f=(d.offsetHeight||0)==3,rt(c),rt(d),f)),b)?g8b:f8b));return a.b.b}
function oLb(a,b){var c,d,e,f;f=lLb(v3(d3(b,Quc),Ruc),a.i);d=k3(v3(b,Ruc),Ytc)?x3(n3(v3(b,Ruc),Quc)):x3(l3(n3(d3(v3(b,Ruc),Quc),Quc),Ytc)?p3(n3(d3(v3(b,Ruc),Quc),Quc)):n3(d3(v3(b,Ruc),Quc),Quc));for(e=0;e<7;++e){c=k3(d3(v3(Quc,n3(b,Quc)),i3(e)),Ytc)?x3(n3(d3(v3(Quc,n3(b,Quc)),i3(e)),Quc)):x3(l3(n3(d3(d3(v3(Quc,n3(b,Quc)),i3(e)),Quc),Quc),Ytc)?p3(n3(d3(d3(v3(Quc,n3(b,Quc)),i3(e)),Quc),Quc)):n3(d3(d3(v3(Quc,n3(b,Quc)),i3(e)),Quc),Quc));yt(nt(a.b.X,e*2),EI(a.d.Cf(v9b(c-3)),1))}nLb(a,EI(a.j.Je(f),154),d,true)}
function qLb(a,b,c,d){jLb();var e;jd.call(this);this.e=a;this.f=b;this.g=d;Eg(hd(this),'\u6700\u70ED\u95E8');e=new fd;Qb(e,(Ze(),ef(),vCc));cd(e,new wlb(wCc));cd(e,new tlb('1.1 3D\u7279\u6548\u7684\u521D\u6B65\u5B9E\u73B0'));cd(e,new wlb(Qvc));cd(e,new wlb(xCc));cd(e,new tlb('1.2 \u624B\u52BF\u6EDA\u52A8\uFF08\u4E2D\uFF09'));cd(e,new tlb('1.3 \u5B8C\u55843D\u7279\u6548\uFF08\u4E2D\uFF09'));Tc(this,e,this.X);id(this,fMb(new hMb(this)));this.d=new jDb;this.d.Df(v9b(0),'GNLEBM-BAM');this.d.Df(v9b(1),'GNLEBM-BBM');this.d.Df(v9b(2),'GNLEBM-BCM');this.d.Df(v9b(3),'GNLEBM-BDM');this.d.Df(v9b(-1),'GNLEBM-BEM');this.d.Df(v9b(-2),'GNLEBM-BFM');this.d.Df(v9b(-3),'GNLEBM-BGM')}
function pMb(a){if(!a.b){a.b=true;Oy('.GNLEBM-BHM{background:black;}.GNLEBM-BIM{position:relative;width:100%;-webkit-transform-style:preserve-3d;height:200px;display:-webkit-box;-webkit-perspective:700;}.GNLEBM-BIM>div>img{-webkit-border-radius:10px 10px;}'+(G5(),I5((P5(),nP))?'.GNLEBM-BIM>div>img{-webkit-box-reflect:below 25px -webkit-gradient(linear,left top,left bottom,from(transparent),color-stop(0.8,transparent),to(rgba(255,255,255,0.7)));}':'.GNLEBM-BIM>div>img{-webkit-box-reflect:below 25px;}')+'.GNLEBM-BIM>div{height:1350px;position:absolute;-webkit-transition:all 0.5s ease-out;cursor:pointer;width:33%;}.GNLEBM-BIM>div>div{display:-webkit-box;-webkit-box-align:center;-webkit-box-pack:center;visibility:hidden;border:1px solid hsl(212,58%,58%);-webkit-border-radius:20px;width:100%;color:white;}');return true}return false}
function lMb(a){if(!a.b){a.b=true;Oy((pG(),'.GNLEBM-BGM{-webkit-opacity:0;left:-10%;}'+(G5(),I5((P5(),nP))?'.GNLEBM-BGM{-webkit-transform:rotateY(55deg) translate(0,50px);}':'.GNLEBM-BGM{-webkit-transform:translate(0,50px);}')+'.GNLEBM-BFM{-webkit-opacity:0.5;left:1%;z-index:0;}'+(I5(nP)?'.GNLEBM-BFM{-webkit-transform:rotateY(55deg) translate(0,55px);}':'.GNLEBM-BFM{-webkit-transform:translate(0,55px);}')+'.GNLEBM-BEM{left:10%;z-index:3;}'+(I5(nP)?'.GNLEBM-BEM{-webkit-transform:rotateY(55deg) translate(20px,25px);}':'.GNLEBM-BEM{-webkit-transform:translate(20px,25px);}')+'.GNLEBM-BAM{left:34%;z-index:10;}'+(I5(nP)?'.GNLEBM-BAM{-webkit-transform:rotateY(0) scale(1.05) translate(0,30px);}':'.GNLEBM-BAM{-webkit-transform:translate(0,30px);}')+'.GNLEBM-BAM>div{visibility:visible !important;}.GNLEBM-BBM{left:58%;-index:3;}'+(I5(nP)?'.GNLEBM-BBM{-webkit-transform:rotateY(-55deg) translate(-20px,25px);}':'.GNLEBM-BBM{-webkit-transform:translate(-20px,25px);}')+'.GNLEBM-BCM{-webkit-opacity:0.5;left:67%;z-index:0;}'+(I5(nP)?'.GNLEBM-BCM{-webkit-transform:rotateY(-55deg) translate(0,55px);}':'.GNLEBM-BCM{-webkit-transform:translate(0,55px);}')+'.GNLEBM-BDM{-webkit-opacity:0;left:78%;}'+(I5(nP)?'.GNLEBM-BDM{-webkit-transform:rotateY(-55deg) translate(0,50px);}':'.GNLEBM-BDM{-webkit-transform:translate(0,50px);}')+Hvc));return true}return false}
var JEc='com.google.gwt.modernizr.client.tests.',HEc='form',EEc='modernizr';var F5;J3(516,1,buc);_.b=null;var K5,L5=null;J3(517,516,buc,Q5);J3(904,29,Suc,qLb);_.sc=function rLb(){return null};_.tc=function sLb(){};_.uc=function tLb(){this.c.X.style[hyc]=(Kv(),Dvc)};_.vc=function uLb(a,b){kLb(this);this.c.X.style[hyc]=(Kv(),jyc);this.c.W.X.style[sEc]=rEc;u5(iLb,'clientWidth:'+$t($doc)+';clientHeight:'+Zt($doc));$()?Gq((tq(),new wLb(this)),500):pLb(this)};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=0;_.j=null;var iLb;J3(905,1,{},wLb);_.Bb=function xLb(){pLb(this.b);return false};_.b=null;J3(906,907,Cuc,PLb);_.dh=function QLb(a){OLb(this,EI(a,157))};_.eh=function RLb(){return h3b(new j3b(this.b.e),this.e)};_.b=null;_.c=0;_.d=false;_.e=null;J3(908,1,ttc,TLb);_.sb=function ULb(a){ijb(a.type)==1&&q6(this.b.b.g,vpc(wpc(EI(this.b.b.f.We(),205),bX.i),vI(v2,Ctc,123,[this.c.Rf()])))};_.b=null;_.c=null;J3(909,907,Cuc,XLb);_.dh=function YLb(a){WLb(this,EI(a,194))};_.eh=function ZLb(){return X1b(this.c,7)};_.b=null;_.c=null;J3(910,1,{},_Lb);_.Bb=function aMb(){var a;if(!this.c.b.S){return false}oLb(this.c.b,(a=this.b,this.b=d3(this.b,Ruc),a));return true};_.b=Tuc;_.c=null;J3(911,1,Uuc,cMb);_.md=function dMb(a){(a.b.clientX||0)<~~($t($doc)/2)?oLb(this.c.b,i3(++this.b)):oLb(this.c.b,i3(--this.b));(this.b>20000||this.b<0)&&(this.b=7001)};_.b=7000;_.c=null;J3(912,1,{},hMb);_.b=null;_.c=null;_.d=null;var iMb=null,jMb=null;J3(914,1,{},mMb);_.fb=function nMb(){return lMb(this)};_.b=false;J3(915,1,{},qMb);_.fb=function rMb(){return pMb(this)};_.b=false;J3(1333,1,zvc);_.Qc=function vnc(){this.c.Lc(Akc(this.b.b))};var OV=L8b(SAc,'BookFlip$1',905,t$),QV=L8b(SAc,'BookFlip$2',906,Q1),PV=L8b(SAc,'BookFlip$2$1',908,t$),TV=L8b(SAc,'BookFlip$3',909,Q1),RV=L8b(SAc,'BookFlip$3$1',910,t$),SV=L8b(SAc,'BookFlip$3$2',911,t$),UV=L8b(SAc,'BookFlip_BinderImpl$Widgets',912,t$),VV=L8b(SAc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',914,t$),WV=L8b(SAc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$2',915,t$),mP=L8b(JEc,'AbstractModernizrTest',516,t$),nP=L8b(JEc,'CssTransforms3d',517,mP);Bvc(Dp)(21);