function DA(){}
function gLb(){}
function kLb(){}
function L4(){H4()}
function p4(a,b){X3(a.b,b)}
function rKb(a){this.b=a}
function WKb(a){this.c=a}
function ZKb(a){this.c=a}
function OKb(a,b){this.b=a;this.c=b}
function SKb(a,b){AKb();this.b=a;this.c=b}
function C4(a){B4();A4.Bf(sO,a)}
function B4(){B4=Zqc;A4=new eCb}
function mLb(){mLb=Zqc;cLb=new gLb}
function nLb(){nLb=Zqc;dLb=new kLb}
function K4(){K4=Zqc;H4();C4(new L4)}
function eKb(){eKb=Zqc;dKb=(n4(),a4(aV.i))}
function BA(){BA=Zqc;AA=new qA(Jzc,new DA)}
function X3(a,b){d4(a,(lgc(),dgc),b,null)}
function nhc(a,b,c,d){return new lKb(a,b,c,d)}
function D4(a){B4();return I4(QH(A4.Af(a),62))}
function aLb(){var a;a=(nLb(),dLb);jLb(a);return a}
function iKb(a,b,c,d){CKb(HKb(new KKb(a,b,c,d),b.Pf(),PX.i))}
function KKb(a,b,c,d){AKb();this.b=a;this.e=b;this.c=c;this.d=d}
function kKb(a){var b;b=new c0b(a.e);CKb(FKb(new SKb(a,b),'issue.all'))}
function oLb(a){var b;b=new d9b;b.b.b+=_tc;b9b(b,D6(a));b.b.b+=auc;return new i6(b.b.b)}
function bLb(a){var b;this.d=a;b=(mLb(),cLb);fLb(b);aLb();this.b=tt($doc);this.c=new w8(this.b)}
function hKb(a){var b,c;for(b=0;b<7;++b){c=gKb(d2(b),a.i);iKb(a,QH(a.j.He(c),150),b,false)}}
function fKb(a){var b;b=vt($doc);vt($doc)>=1024?Tb(a.c,xtc+b*0.33*2+iuc):Tb(a.c,xtc+b*0.33*2+iuc)}
function CA(a,b){(a.b.clientX||0)<~~(vt($doc)/2)?jKb(b.c.b,d2(++b.b)):jKb(b.c.b,d2(--b.b));(b.b>20000||b.b<0)&&(b.b=7001)}
function RKb(a,b){a.b.j=b;a.b.i==0&&(a.b.i=a.b.j.Pe());hKb(a.b);cq((Rp(),new WKb(a)),5000);fc(a.b.b,new ZKb(a),(BA(),BA(),AA))}
function gKb(a,b){return f2(a,Prc)?s2(i2(a,d2(b))):s2(g2(i2($1(a,d2(b)),d2(b)),Prc)?k2(i2($1(a,d2(b)),d2(b))):i2($1(a,d2(b)),d2(b)))}
function pLb(a,b){var c;c=new d9b;c.b.b+=Wzc;b9b(c,D6(a.b));c.b.b+="\" width='100%' ><div>";b9b(c,D6(b));c.b.b+=Xzc;return new i6(c.b.b)}
function H4(){H4=Zqc;F4=$doc.createElement(Kzc);G4=new eCb;G4.Bf(Lzc,Mzc);G4.Bf(xvc,Mzc);G4.Bf('submit',Nzc);G4.Bf('reset',Nzc);G4.Bf(Lvc,Ozc);G4.Bf(Evc,Ozc);G4.Bf('abort',Ozc)}
function JKb(a,b){var c,d;d=pLb((eKb(),I6(),new F6(Uzc+b.wh().c+Vzc+b.uh())),a.e.gh());c=Ls(a.b.b.X,a.c*2);Xs(c,d.b);a.d?Ws(c,QH(a.b.d.Af(w7b(3)),1)):Ws(c,QH(a.b.d.Af(w7b(a.c-3)),1));sib(c,1);fib(c,new OKb(a,a.e));fKb(a.b)}
function yic(a){!a.v&&(a.v=nhc((!a.N&&(a.N=(!a.M&&(a.M=Phc(new rNb,(!a.q&&(a.q=new BC),a.q),(!a.u&&(a.u=(!a.W&&(a.W=ric(a)),a.W)),a.u))),a.M)),a.N),new Ckc(a),(!a.Z&&(a.Z=uic(a)),a.Z),(!a.k&&(a.k=Xic(new Jnc,(!a.q&&(a.q=new BC),a.q))),a.k)));return a.v}
function _Kb(a){var b,c,d,e;c=new xkb(oLb(a.b).b);b=y8(c.X);v8(a.c);b.c?Ms(b.c,b.b,b.d):B8(b.b);ukb(c,(d=new xkb((e=new d9b,e.b.b+='<div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div>',new i6(e.b.b)).b),Ub(d,xtc+(aLb(),'GNLEBM-BJM')+xtc),a.d.b=d,d),v8(a.c));a.d.c=c;return c}
function I4(a){var b,c,d,e,f;!a.b&&(a.b=(i6b(),(b=(H4(),F4).style['perspectiveProperty']!==undefined||F4.style['WebkitPerspective']!==undefined,b&&(b=(c=$doc.createElement(Puc),d=$doc.createElement(Wtc),c['textContent']='@media (-webkit-transform-3d),(modernizr){#modernizr{height:3px}}',e=$doc.getElementsByTagName(Quc)[0],e.appendChild(c),d.id=Kzc,Ks($doc.documentElement,d),f=(d.offsetHeight||0)==3,Ps(c),Ps(d),f)),b)?h6b:g6b));return a.b.b}
function jKb(a,b){var c,d,e,f;f=gKb(q2($1(b,Hsc),Isc),a.i);d=f2(q2(b,Isc),Prc)?s2(i2(q2(b,Isc),Hsc)):s2(g2(i2($1(q2(b,Isc),Hsc),Hsc),Prc)?k2(i2($1(q2(b,Isc),Hsc),Hsc)):i2($1(q2(b,Isc),Hsc),Hsc));for(e=0;e<7;++e){c=f2($1(q2(Hsc,i2(b,Hsc)),d2(e)),Prc)?s2(i2($1(q2(Hsc,i2(b,Hsc)),d2(e)),Hsc)):s2(g2(i2($1($1(q2(Hsc,i2(b,Hsc)),d2(e)),Hsc),Hsc),Prc)?k2(i2($1($1(q2(Hsc,i2(b,Hsc)),d2(e)),Hsc),Hsc)):i2($1($1(q2(Hsc,i2(b,Hsc)),d2(e)),Hsc),Hsc));Ws(Ls(a.b.X,e*2),QH(a.d.Af(w7b(c-3)),1))}iKb(a,QH(a.j.He(f),150),d,true)}
function lKb(a,b,c,d){eKb();var e;hd.call(this);this.e=a;this.f=b;this.g=d;sg(fd(this),'\u6700\u70ED\u95E8');e=new dd;Qb(e,(Ne(),Ue(),Pzc));ad(e,new rkb(Qzc));ad(e,new okb('1.1 3D\u7279\u6548\u7684\u521D\u6B65\u5B9E\u73B0'));ad(e,new rkb(Gtc));ad(e,new rkb(Rzc));ad(e,new okb('1.2 \u624B\u52BF\u6EDA\u52A8\uFF08\u4E2D\uFF09'));ad(e,new okb('1.3 \u5B8C\u55843D\u7279\u6548\uFF08\u4E2D\uFF09'));Rc(this,e,this.X);gd(this,_Kb(new bLb(this)));this.d=new eCb;this.d.Bf(w7b(0),'GNLEBM-BBM');this.d.Bf(w7b(1),'GNLEBM-BCM');this.d.Bf(w7b(2),'GNLEBM-BDM');this.d.Bf(w7b(3),'GNLEBM-BEM');this.d.Bf(w7b(-1),'GNLEBM-BFM');this.d.Bf(w7b(-2),'GNLEBM-BGM');this.d.Bf(w7b(-3),'GNLEBM-BHM')}
function jLb(a){if(!a.b){a.b=true;jy('.GNLEBM-BIM{background:black;}.GNLEBM-BJM{position:relative;width:100%;-webkit-transform-style:preserve-3d;height:200px;display:-webkit-box;-webkit-perspective:700;}.GNLEBM-BJM>div>img{-webkit-border-radius:10px 10px;}'+(B4(),D4((K4(),sO))?'.GNLEBM-BJM>div>img{-webkit-box-reflect:below 25px -webkit-gradient(linear,left top,left bottom,from(transparent),color-stop(0.8,transparent),to(rgba(255,255,255,0.7)));}':'.GNLEBM-BJM>div>img{-webkit-box-reflect:below 25px;}')+'.GNLEBM-BJM>div{height:1350px;position:absolute;-webkit-transition:all 0.5s ease-out;cursor:pointer;width:33%;}.GNLEBM-BJM>div>div{display:-webkit-box;-webkit-box-align:center;-webkit-box-pack:center;visibility:hidden;border:1px solid hsl(212,58%,58%);-webkit-border-radius:20px;width:100%;color:white;}');return true}return false}
function fLb(a){if(!a.b){a.b=true;jy((BF(),'.GNLEBM-BHM{-webkit-opacity:0;left:-10%;}'+(B4(),D4((K4(),sO))?'.GNLEBM-BHM{-webkit-transform:rotateY(55deg) translate(0,50px);}':'.GNLEBM-BHM{-webkit-transform:translate(0,50px);}')+'.GNLEBM-BGM{-webkit-opacity:0.5;left:1%;z-index:0;}'+(D4(sO)?'.GNLEBM-BGM{-webkit-transform:rotateY(55deg) translate(0,55px);}':'.GNLEBM-BGM{-webkit-transform:translate(0,55px);}')+'.GNLEBM-BFM{left:10%;z-index:3;}'+(D4(sO)?'.GNLEBM-BFM{-webkit-transform:rotateY(55deg) translate(20px,25px);}':'.GNLEBM-BFM{-webkit-transform:translate(20px,25px);}')+'.GNLEBM-BBM{left:34%;z-index:10;}'+(D4(sO)?'.GNLEBM-BBM{-webkit-transform:rotateY(0) scale(1.05) translate(0,30px);}':'.GNLEBM-BBM{-webkit-transform:translate(0,30px);}')+'.GNLEBM-BBM>div{visibility:visible !important;}.GNLEBM-BCM{left:58%;-index:3;}'+(D4(sO)?'.GNLEBM-BCM{-webkit-transform:rotateY(-55deg) translate(-20px,25px);}':'.GNLEBM-BCM{-webkit-transform:translate(-20px,25px);}')+'.GNLEBM-BDM{-webkit-opacity:0.5;left:67%;z-index:0;}'+(D4(sO)?'.GNLEBM-BDM{-webkit-transform:rotateY(-55deg) translate(0,55px);}':'.GNLEBM-BDM{-webkit-transform:translate(0,55px);}')+'.GNLEBM-BEM{-webkit-opacity:0;left:78%;}'+(D4(sO)?'.GNLEBM-BEM{-webkit-transform:rotateY(-55deg) translate(0,50px);}':'.GNLEBM-BEM{-webkit-transform:translate(0,50px);}')+xtc));return true}return false}
var Zzc='com.google.gwt.modernizr.client.tests.',Nzc='form',Kzc='modernizr';E2(400,390,{});E2(401,400,{},DA);_.ed=function EA(a){CA(this,QH(a,33))};_.hd=function FA(){return AA};var AA;var A4;E2(501,1,Urc);_.b=null;var F4,G4=null;E2(502,501,Urc,L4);E2(889,29,Jsc,lKb);_.rc=function mKb(){return null};_.sc=function nKb(){};_.tc=function oKb(){this.c.X.style[Zvc]=(fv(),ttc)};_.uc=function pKb(a,b){fKb(this);this.c.X.style[Zvc]=(fv(),_vc);this.c.W.X.style[Szc]=Tzc;p4(dKb,'clientWidth:'+vt($doc)+';clientHeight:'+ut($doc));$()?cq((Rp(),new rKb(this)),500):kKb(this)};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=0;_.j=null;var dKb;E2(890,1,{},rKb);_.zb=function sKb(){kKb(this.b);return false};_.b=null;E2(891,892,tsc,KKb);_.bh=function LKb(a){JKb(this,QH(a,153))};_.ch=function MKb(){return l1b(new n1b(this.b.e),this.e)};_.b=null;_.c=0;_.d=false;_.e=null;E2(893,1,krc,OKb);_.rb=function PKb(a){dib(a.type)==1&&l5(this.b.b.g,mnc(nnc(QH(this.b.b.f.Ue(),201),eW.i),HH(q1,trc,121,[this.c.Pf()])))};_.b=null;_.c=null;E2(894,892,tsc,SKb);_.bh=function TKb(a){RKb(this,QH(a,190))};_.ch=function UKb(){return __b(this.c,7)};_.b=null;_.c=null;E2(895,1,{},WKb);_.zb=function XKb(){var a;if(!this.c.b.S){return false}jKb(this.c.b,(a=this.b,this.b=$1(this.b,Isc),a));return true};_.b=Ksc;_.c=null;E2(896,1,{33:1,46:1},ZKb);_.b=7000;_.c=null;E2(897,1,{},bLb);_.b=null;_.c=null;_.d=null;var cLb=null,dLb=null;E2(899,1,{},gLb);_.eb=function hLb(){return fLb(this)};_.b=false;E2(900,1,{},kLb);_.eb=function lLb(){return jLb(this)};_.b=false;E2(1318,1,ptc);_.Pc=function Qlc(){this.c.Kc(yic(this.b.b))};var TU=M6b(Nyc,'BookFlip$1',890,qZ),VU=M6b(Nyc,'BookFlip$2',891,L0),UU=M6b(Nyc,'BookFlip$2$1',893,qZ),YU=M6b(Nyc,'BookFlip$3',894,L0),WU=M6b(Nyc,'BookFlip$3$1',895,qZ),XU=M6b(Nyc,'BookFlip$3$2',896,qZ),ZU=M6b(Nyc,'BookFlip_BinderImpl$Widgets',897,qZ),QM=M6b(Yzc,'DragDropEventBase',400,OM),RM=M6b(Yzc,'DragStartEvent',401,QM),$U=M6b(Nyc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',899,qZ),_U=M6b(Nyc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$2',900,qZ),rO=M6b(Zzc,'AbstractModernizrTest',501,qZ),sO=M6b(Zzc,'CssTransforms3d',502,rO);rtc(_o)(1);