function Cz(){}
function aKb(){}
function eKb(){}
function u3(){q3()}
function lJb(a){this.b=a}
function QJb(a){this.c=a}
function TJb(a){this.c=a}
function $2(a,b){G2(a.b,b)}
function l3(a){k3();j3.Ef(fN,a)}
function k3(){k3=vpc;j3=new $Ab}
function gKb(){gKb=vpc;YJb=new aKb}
function hKb(){hKb=vpc;ZJb=new eKb}
function t3(){t3=vpc;q3();l3(new u3)}
function Az(){Az=vpc;zz=new wz(wAc,new Cz)}
function $Ib(){$Ib=vpc;ZIb=(Y2(),L2(QT.i))}
function IJb(a,b){this.b=a;this.c=b}
function MJb(a,b){uJb();this.b=a;this.c=b}
function EJb(a,b,c,d){uJb();this.b=a;this.e=b;this.c=c;this.d=d}
function cJb(a,b,c,d){wJb(BJb(new EJb(a,b,c,d),b.Sf(),BW.i))}
function Vfc(a,b,c,d){return new fJb(a,b,c,d)}
function m3(a){k3();return r3(PG(j3.Df(a),60))}
function G2(a,b){O2(a,(Uec(),Mec),b,null)}
function WJb(){var a;a=(hKb(),ZJb);dKb(a);return a}
function eJb(a){var b;b=new M$b(a.e);wJb(zJb(new MJb(a,b),'issue.all'))}
function iKb(a){var b;b=new M7b;b.b.b+=wsc;K7b(b,m5(a));b.b.b+=xsc;return new T4(b.b.b)}
function XJb(a){var b;this.d=a;b=(gKb(),YJb);_Jb(b);WJb();this.b=Ps($doc);this.c=new f7(this.b)}
function bJb(a){var b,c;for(b=0;b<7;++b){c=aJb(O0(b),a.i);cJb(a,PG(a.j.He(c),148),b,false)}}
function _Ib(a){var b;b=Rs($doc);Rs($doc)>=1024?Xb(a.c,Urc+b*0.33*2+Fsc):Xb(a.c,Urc+b*0.33*2+Fsc)}
function Bz(a,b){(a.b.clientX||0)<~~(Rs($doc)/2)?dJb(b.c.b,O0(++b.b)):dJb(b.c.b,O0(--b.b));(b.b>20000||b.b<0)&&(b.b=7001)}
function LJb(a,b){a.b.j=b;a.b.i==0&&(a.b.i=a.b.j.Pe());bJb(a.b);zp((mp(),new QJb(a)),5000);jc(a.b.b,new TJb(a),(Az(),Az(),zz))}
function aJb(a,b){return Q0(a,kqc)?b1(T0(a,O0(b))):b1(R0(T0(J0(a,O0(b)),O0(b)),kqc)?V0(T0(J0(a,O0(b)),O0(b))):T0(J0(a,O0(b)),O0(b)))}
function jKb(a,b){var c;c=new M7b;c.b.b+=EAc;K7b(c,m5(a.b));c.b.b+="\" width='100%' ><div>";K7b(c,m5(b));c.b.b+=Myc;return new T4(c.b.b)}
function q3(){q3=vpc;o3=$doc.createElement(xAc);p3=new $Ab;p3.Ef(yAc,zAc);p3.Ef(Utc,zAc);p3.Ef('submit',AAc);p3.Ef('reset',AAc);p3.Ef(guc,BAc);p3.Ef(_tc,BAc);p3.Ef('abort',BAc)}
function DJb(a,b){var c,d;d=jKb(($Ib(),r5(),new o5(CAc+b.zh().c+DAc+b.xh())),a.e.jh());c=gs(a.b.b.X,a.c*2);ss(c,d.b);a.d?rs(c,PG(a.b.d.Df(d6b(3)),1)):rs(c,PG(a.b.d.Df(d6b(a.c-3)),1));bhb(c,1);Qgb(c,new IJb(a,a.e));_Ib(a.b)}
function dhc(a){!a.v&&(a.v=Vfc((!a.N&&(a.N=(!a.M&&(a.M=ugc(new lMb,(!a.q&&(a.q=new AB),a.q),(!a.u&&(a.u=(!a.W&&(a.W=Ygc(a)),a.W)),a.u))),a.M)),a.N),new pjc(a),(!a.Z&&(a.Z=_gc(a)),a.Z),(!a.k&&(a.k=Chc(new gmc,(!a.q&&(a.q=new AB),a.q))),a.k)));return a.v}
function VJb(a){var b,c,d,e;c=new gjb(iKb(a.b).b);b=h7(c.X);e7(a.c);b.c?hs(b.c,b.b,b.d):k7(b.b);djb(c,(d=new gjb((e=new M7b,e.b.b+='<div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div>',new T4(e.b.b)).b),Yb(d,Urc+(WJb(),'GCEHXR-BNM')+Urc),a.d.b=d,d),e7(a.c));a.d.c=c;return c}
function r3(a){var b,c,d,e,f;!a.b&&(a.b=(R4b(),(b=(q3(),o3).style['perspectiveProperty']!==undefined||o3.style['WebkitPerspective']!==undefined,b&&(b=(c=$doc.createElement(ktc),d=$doc.createElement(rsc),c['textContent']='@media (-webkit-transform-3d),(modernizr){#modernizr{height:3px}}',e=$doc.getElementsByTagName(ltc)[0],e.appendChild(c),d.id=xAc,fs($doc.documentElement,d),f=(d.offsetHeight||0)==3,ks(c),ks(d),f)),b)?Q4b:P4b));return a.b.b}
function dJb(a,b){var c,d,e,f;f=aJb(_0(J0(b,crc),drc),a.i);d=Q0(_0(b,drc),kqc)?b1(T0(_0(b,drc),crc)):b1(R0(T0(J0(_0(b,drc),crc),crc),kqc)?V0(T0(J0(_0(b,drc),crc),crc)):T0(J0(_0(b,drc),crc),crc));for(e=0;e<7;++e){c=Q0(J0(_0(crc,T0(b,crc)),O0(e)),kqc)?b1(T0(J0(_0(crc,T0(b,crc)),O0(e)),crc)):b1(R0(T0(J0(J0(_0(crc,T0(b,crc)),O0(e)),crc),crc),kqc)?V0(T0(J0(J0(_0(crc,T0(b,crc)),O0(e)),crc),crc)):T0(J0(J0(_0(crc,T0(b,crc)),O0(e)),crc),crc));rs(gs(a.b.X,e*2),PG(a.d.Df(d6b(c-3)),1))}cJb(a,PG(a.j.He(f),148),d,true)}
function fJb(a,b,c,d){$Ib();var e;kd.call(this);this.e=a;this.f=b;this.g=d;vg(id(this),'\u6700\u70ED\u95E8');e=new gd;Ub(e,(Qe(),Xe(),Fyc));dd(e,new ajb(Gyc));dd(e,new Zib('1.1 3D\u7279\u6548\u7684\u521D\u6B65\u5B9E\u73B0'));dd(e,new ajb(bsc));dd(e,new ajb(Hyc));dd(e,new Zib('1.2 \u624B\u52BF\u6EDA\u52A8\uFF08\u4E2D\uFF09'));dd(e,new Zib('1.3 \u5B8C\u55843D\u7279\u6548\uFF08\u4E2D\uFF09'));Uc(this,e,this.X);jd(this,VJb(new XJb(this)));this.d=new $Ab;this.d.Ef(d6b(0),'GCEHXR-BFM');this.d.Ef(d6b(1),'GCEHXR-BGM');this.d.Ef(d6b(2),'GCEHXR-BHM');this.d.Ef(d6b(3),'GCEHXR-BIM');this.d.Ef(d6b(-1),'GCEHXR-BJM');this.d.Ef(d6b(-2),'GCEHXR-BKM');this.d.Ef(d6b(-3),'GCEHXR-BLM')}
function dKb(a){if(!a.b){a.b=true;px('.GCEHXR-BMM{background:black;}.GCEHXR-BNM{position:relative;width:100%;-webkit-transform-style:preserve-3d;height:200px;display:-webkit-box;-webkit-perspective:700;}'+(k3(),m3((t3(),fN))?'.GCEHXR-BNM>div>img{-webkit-border-radius:10px 10px;-webkit-box-reflect:below 25px -webkit-gradient(linear,left top,left bottom,from(transparent),color-stop(0.8,transparent),to(rgba(255,255,255,0.7)));}':'.GCEHXR-BNM>div>img{-webkit-border-radius:10px 10px;-webkit-box-reflect:below 25px;}')+'.GCEHXR-BNM>div{height:1350px;position:absolute;-webkit-transition:all 0.5s ease-out;cursor:pointer;width:33%;}.GCEHXR-BNM>div>div{display:-webkit-box;-webkit-box-align:center;-webkit-box-pack:center;visibility:hidden;border:1px solid hsl(212,58%,58%);-webkit-border-radius:20px;width:100%;color:white;}');return true}return false}
function _Jb(a){if(!a.b){a.b=true;px((AE(),Urc+(k3(),m3((t3(),fN))?'.GCEHXR-BLM{-webkit-transform:rotateY(55deg) translate(0,50px);-webkit-opacity:0;left:-10%;}':'.GCEHXR-BLM{-webkit-transform:translate(0,50px);-webkit-opacity:0;left:-10%;}')+(m3(fN)?'.GCEHXR-BKM{-webkit-transform:rotateY(55deg) translate(0,55px);-webkit-opacity:0.5;left:1%;z-index:0;}':'.GCEHXR-BKM{-webkit-transform:translate(0,55px);-webkit-opacity:0.5;left:1%;z-index:0;}')+(m3(fN)?'.GCEHXR-BJM{-webkit-transform:rotateY(55deg) translate(20px,25px);left:10%;z-index:3;}':'.GCEHXR-BJM{-webkit-transform:translate(20px,25px);left:10%;z-index:3;}')+(m3(fN)?'.GCEHXR-BFM{-webkit-transform:rotateY(0) scale(1.05) translate(0,30px);left:34%;z-index:10;}':'.GCEHXR-BFM{-webkit-transform:translate(0,30px);left:34%;z-index:10;}')+'.GCEHXR-BFM>div{visibility:visible !important;}'+(m3(fN)?'.GCEHXR-BGM{-webkit-transform:rotateY(-55deg) translate(-20px,25px);left:58%;z-index:3;}':'.GCEHXR-BGM{-webkit-transform:translate(-20px,25px);left:58%;z-index:3;}')+(m3(fN)?'.GCEHXR-BHM{-webkit-transform:rotateY(-55deg) translate(0,55px);-webkit-opacity:0.5;left:67%;z-index:0;}':'.GCEHXR-BHM{-webkit-transform:translate(0,55px);-webkit-opacity:0.5;left:67%;z-index:0;}')+(m3(fN)?'.GCEHXR-BIM{-webkit-transform:rotateY(-55deg) translate(0,50px);-webkit-opacity:0;left:78%;}':'.GCEHXR-BIM{-webkit-transform:translate(0,50px);-webkit-opacity:0;left:78%;}')+Urc));return true}return false}
var GAc='com.google.gwt.modernizr.client.tests.',AAc='form',xAc='modernizr';n1(377,368,{});n1(378,377,{},Cz);_.ed=function Dz(a){Bz(this,PG(a,31))};_.hd=function Ez(){return zz};var zz;var j3;n1(478,1,pqc);_.b=null;var o3,p3=null;n1(479,478,pqc,u3);n1(867,29,erc,fJb);_.rc=function gJb(){return null};_.sc=function hJb(){};_.tc=function iJb(){this.c.X.style[uuc]=(Bu(),Qrc)};_.uc=function jJb(a,b){_Ib(this);this.c.X.style[uuc]=(Bu(),wuc);this.c.W.X.style[kzc]=jzc;$2(ZIb,'clientWidth:'+Rs($doc)+';clientHeight:'+Qs($doc));db()?zp((mp(),new lJb(this)),500):eJb(this)};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=0;_.j=null;var ZIb;n1(868,1,{},lJb);_.zb=function mJb(){eJb(this.b);return false};_.b=null;n1(869,870,Qqc,EJb);_.eh=function FJb(a){DJb(this,PG(a,151))};_.fh=function GJb(){return V_b(new X_b(this.b.e),this.e)};_.b=null;_.c=0;_.d=false;_.e=null;n1(871,1,Ipc,IJb);_.rb=function JJb(a){Ogb(a.type)==1&&W3(this.b.b.g,Llc(Mlc(PG(this.b.b.f.Xe(),199),VU.i),GG(__,Rpc,119,[this.c.Sf()])))};_.b=null;_.c=null;n1(872,870,Qqc,MJb);_.eh=function NJb(a){LJb(this,PG(a,188))};_.fh=function OJb(){return J$b(this.c,7)};_.b=null;_.c=null;n1(873,1,{},QJb);_.zb=function RJb(){var a;if(!this.c.b.S){return false}dJb(this.c.b,(a=this.b,this.b=J0(this.b,drc),a));return true};_.b=frc;_.c=null;n1(874,1,{31:1,44:1},TJb);_.b=7000;_.c=null;n1(875,1,{},XJb);_.b=null;_.c=null;_.d=null;var YJb=null,ZJb=null;n1(877,1,{},aKb);_.eb=function bKb(){return _Jb(this)};_.b=false;n1(878,1,{},eKb);_.eb=function fKb(){return dKb(this)};_.b=false;n1(1280,1,Mrc);_.Pc=function Jjc(){vlc(this.c,dhc(this.b.b))};var HT=t5b($wc,'BookFlip$1',868,cY),JT=t5b($wc,'BookFlip$2',869,v_),IT=t5b($wc,'BookFlip$2$1',871,cY),MT=t5b($wc,'BookFlip$3',872,v_),KT=t5b($wc,'BookFlip$3$1',873,cY),LT=t5b($wc,'BookFlip$3$2',874,cY),NT=t5b($wc,'BookFlip_BinderImpl$Widgets',875,cY),CL=t5b(FAc,'DragDropEventBase',377,BL),DL=t5b(FAc,'DragStartEvent',378,CL),OT=t5b($wc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',877,cY),PT=t5b($wc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$2',878,cY),eN=t5b(GAc,'AbstractModernizrTest',478,cY),fN=t5b(GAc,'CssTransforms3d',479,eN);Orc(wo)(18);