function eB(){}
function VLb(){}
function ZLb(){}
function y5(){u5()}
function c5(a,b){K4(a.b,b)}
function eLb(a){this.b=a}
function JLb(a){this.c=a}
function MLb(a){this.c=a}
function BLb(a,b){this.b=a;this.c=b}
function FLb(a,b){nLb();this.b=a;this.c=b}
function _Lb(){_Lb=Hsc;RLb=new VLb}
function aMb(){aMb=Hsc;SLb=new ZLb}
function o5(){o5=Hsc;n5=new TCb}
function x5(){x5=Hsc;u5();p5(new y5)}
function p5(a){o5();n5.Cf($O,a)}
function q5(a){o5();return v5(rI(n5.Bf(a),62))}
function Nic(a,b,c,d){return new $Kb(a,b,c,d)}
function XKb(a,b,c,d){pLb(uLb(new xLb(a,b,c,d),b.Qf(),AY.i))}
function K4(a,b){S4(a,(Lhc(),Dhc),b,null)}
function TKb(){TKb=Hsc;SKb=(a5(),P4(IV.i))}
function cB(){cB=Hsc;bB=new TA(jDc,new eB)}
function PLb(){var a;a=(aMb(),SLb);YLb(a);return a}
function ZKb(a){var b;b=new z1b(a.e);pLb(sLb(new FLb(a,b),'issue.all'))}
function xLb(a,b,c,d){nLb();this.b=a;this.e=b;this.c=c;this.d=d}
function QLb(a){var b;this.d=a;b=(_Lb(),RLb);ULb(b);PLb();this.b=Xt($doc);this.c=new j9(this.b)}
function bMb(a){var b;b=new Dac;b.b.b+=Jvc;Bac(b,q7(a));b.b.b+=Kvc;return new X6(b.b.b)}
function cMb(a,b){var c;c=new Dac;c.b.b+=hCc;Bac(c,q7(a.b));c.b.b+="\" width='100%' ><div>";Bac(c,q7(b));c.b.b+=nCc;return new X6(c.b.b)}
function WKb(a){var b,c;for(b=0;b<7;++b){c=VKb(S2(b),a.i);XKb(a,rI(a.j.Ie(c),151),b,false)}}
function UKb(a){var b;b=Zt($doc);Zt($doc)>=1024?Ub(a.c,fvc+b*0.33*2+Svc):Ub(a.c,fvc+b*0.33*2+Svc)}
function dB(a,b){(a.b.clientX||0)<~~(Zt($doc)/2)?YKb(b.c.b,S2(++b.b)):YKb(b.c.b,S2(--b.b));(b.b>20000||b.b<0)&&(b.b=7001)}
function ELb(a,b){a.b.j=b;a.b.i==0&&(a.b.i=a.b.j.Qe());WKb(a.b);Gq((tq(),new JLb(a)),5000);gc(a.b.b,new MLb(a),(cB(),cB(),bB))}
function VKb(a,b){return U2(a,xtc)?f3(X2(a,S2(b))):f3(V2(X2(N2(a,S2(b)),S2(b)),xtc)?Z2(X2(N2(a,S2(b)),S2(b))):X2(N2(a,S2(b)),S2(b)))}
function u5(){u5=Hsc;s5=$doc.createElement(kDc);t5=new TCb;t5.Cf(lDc,mDc);t5.Cf(fxc,mDc);t5.Cf('submit',nDc);t5.Cf('reset',nDc);t5.Cf(txc,oDc);t5.Cf(mxc,oDc);t5.Cf('abort',oDc)}
function wLb(a,b){var c,d;d=cMb((TKb(),v7(),new s7(aCc+b.xh().c+bCc+b.vh())),a.e.hh());c=nt(a.b.b.X,a.c*2);zt(c,d.b);a.d?yt(c,rI(a.b.d.Bf(W8b(3)),1)):yt(c,rI(a.b.d.Bf(W8b(a.c-3)),1));fjb(c,1);Uib(c,new BLb(a,a.e));UKb(a.b)}
function _jc(a){!a.v&&(a.v=Nic((!a.O&&(a.O=(!a.N&&(a.N=pjc(new tOb,(!a.q&&(a.q=new cD),a.q),(!a.u&&(a.u=(!a.X&&(a.X=Ujc(a)),a.X)),a.u))),a.N)),a.O),new tnc(a),(!a.$&&(a.$=Xjc(a)),a.$),(!a.k&&(a.k=ykc(new rpc,(!a.q&&(a.q=new cD),a.q))),a.k)));return a.v}
function OLb(a){var b,c,d,e;c=new klb(bMb(a.b).b);b=l9(c.X);i9(a.c);b.c?ot(b.c,b.b,b.d):o9(b.b);hlb(c,(d=new klb((e=new Dac,e.b.b+='<div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div>',new X6(e.b.b)).b),Vb(d,fvc+(PLb(),'GNLEBM-BOM')+fvc),a.d.b=d,d),i9(a.c));a.d.c=c;return c}
function v5(a){var b,c,d,e,f;!a.b&&(a.b=(I7b(),(b=(u5(),s5).style['perspectiveProperty']!==undefined||s5.style['WebkitPerspective']!==undefined,b&&(b=(c=$doc.createElement(xwc),d=$doc.createElement(Evc),c['textContent']='@media (-webkit-transform-3d),(modernizr){#modernizr{height:3px}}',e=$doc.getElementsByTagName(ywc)[0],e.appendChild(c),d.id=kDc,mt($doc.documentElement,d),f=(d.offsetHeight||0)==3,rt(c),rt(d),f)),b)?H7b:G7b));return a.b.b}
function YKb(a,b){var c,d,e,f;f=VKb(d3(N2(b,puc),quc),a.i);d=U2(d3(b,quc),xtc)?f3(X2(d3(b,quc),puc)):f3(V2(X2(N2(d3(b,quc),puc),puc),xtc)?Z2(X2(N2(d3(b,quc),puc),puc)):X2(N2(d3(b,quc),puc),puc));for(e=0;e<7;++e){c=U2(N2(d3(puc,X2(b,puc)),S2(e)),xtc)?f3(X2(N2(d3(puc,X2(b,puc)),S2(e)),puc)):f3(V2(X2(N2(N2(d3(puc,X2(b,puc)),S2(e)),puc),puc),xtc)?Z2(X2(N2(N2(d3(puc,X2(b,puc)),S2(e)),puc),puc)):X2(N2(N2(d3(puc,X2(b,puc)),S2(e)),puc),puc));yt(nt(a.b.X,e*2),rI(a.d.Bf(W8b(c-3)),1))}XKb(a,rI(a.j.Ie(f),151),d,true)}
function $Kb(a,b,c,d){TKb();var e;jd.call(this);this.e=a;this.f=b;this.g=d;Eg(hd(this),'\u6700\u70ED\u95E8');e=new fd;Qb(e,(Ze(),ef(),SBc));cd(e,new elb(TBc));cd(e,new blb('1.1 3D\u7279\u6548\u7684\u521D\u6B65\u5B9E\u73B0'));cd(e,new elb(ovc));cd(e,new elb(UBc));cd(e,new blb('1.2 \u624B\u52BF\u6EDA\u52A8\uFF08\u4E2D\uFF09'));cd(e,new blb('1.3 \u5B8C\u55843D\u7279\u6548\uFF08\u4E2D\uFF09'));Tc(this,e,this.X);id(this,OLb(new QLb(this)));this.d=new TCb;this.d.Cf(W8b(0),'GNLEBM-BGM');this.d.Cf(W8b(1),'GNLEBM-BHM');this.d.Cf(W8b(2),'GNLEBM-BIM');this.d.Cf(W8b(3),'GNLEBM-BJM');this.d.Cf(W8b(-1),'GNLEBM-BKM');this.d.Cf(W8b(-2),'GNLEBM-BLM');this.d.Cf(W8b(-3),'GNLEBM-BMM')}
function YLb(a){if(!a.b){a.b=true;Ny('.GNLEBM-BNM{background:black;}.GNLEBM-BOM{position:relative;width:100%;-webkit-transform-style:preserve-3d;height:200px;display:-webkit-box;-webkit-perspective:700;}.GNLEBM-BOM>div>img{-webkit-border-radius:10px 10px;}'+(o5(),q5((x5(),$O))?'.GNLEBM-BOM>div>img{-webkit-box-reflect:below 25px -webkit-gradient(linear,left top,left bottom,from(transparent),color-stop(0.8,transparent),to(rgba(255,255,255,0.7)));}':'.GNLEBM-BOM>div>img{-webkit-box-reflect:below 25px;}')+'.GNLEBM-BOM>div{height:1350px;position:absolute;-webkit-transition:all 0.5s ease-out;cursor:pointer;width:33%;}.GNLEBM-BOM>div>div{display:-webkit-box;-webkit-box-align:center;-webkit-box-pack:center;visibility:hidden;border:1px solid hsl(212,58%,58%);-webkit-border-radius:20px;width:100%;color:white;}');return true}return false}
function ULb(a){if(!a.b){a.b=true;Ny((cG(),'.GNLEBM-BMM{-webkit-opacity:0;left:-10%;}'+(o5(),q5((x5(),$O))?'.GNLEBM-BMM{-webkit-transform:rotateY(55deg) translate(0,50px);}':'.GNLEBM-BMM{-webkit-transform:translate(0,50px);}')+'.GNLEBM-BLM{-webkit-opacity:0.5;left:1%;z-index:0;}'+(q5($O)?'.GNLEBM-BLM{-webkit-transform:rotateY(55deg) translate(0,55px);}':'.GNLEBM-BLM{-webkit-transform:translate(0,55px);}')+'.GNLEBM-BKM{left:10%;z-index:3;}'+(q5($O)?'.GNLEBM-BKM{-webkit-transform:rotateY(55deg) translate(20px,25px);}':'.GNLEBM-BKM{-webkit-transform:translate(20px,25px);}')+'.GNLEBM-BGM{left:34%;z-index:10;}'+(q5($O)?'.GNLEBM-BGM{-webkit-transform:rotateY(0) scale(1.05) translate(0,30px);}':'.GNLEBM-BGM{-webkit-transform:translate(0,30px);}')+'.GNLEBM-BGM>div{visibility:visible !important;}.GNLEBM-BHM{left:58%;-index:3;}'+(q5($O)?'.GNLEBM-BHM{-webkit-transform:rotateY(-55deg) translate(-20px,25px);}':'.GNLEBM-BHM{-webkit-transform:translate(-20px,25px);}')+'.GNLEBM-BIM{-webkit-opacity:0.5;left:67%;z-index:0;}'+(q5($O)?'.GNLEBM-BIM{-webkit-transform:rotateY(-55deg) translate(0,55px);}':'.GNLEBM-BIM{-webkit-transform:translate(0,55px);}')+'.GNLEBM-BJM{-webkit-opacity:0;left:78%;}'+(q5($O)?'.GNLEBM-BJM{-webkit-transform:rotateY(-55deg) translate(0,50px);}':'.GNLEBM-BJM{-webkit-transform:translate(0,50px);}')+fvc));return true}return false}
var qDc='com.google.gwt.modernizr.client.tests.',nDc='form',kDc='modernizr';r3(413,403,{});r3(414,413,{},eB);_.fd=function fB(a){dB(this,rI(a,33))};_.jd=function gB(){return bB};var bB;var n5;r3(514,1,Ctc);_.b=null;var s5,t5=null;r3(515,514,Ctc,y5);r3(902,29,ruc,$Kb);_.sc=function _Kb(){return null};_.tc=function aLb(){};_.uc=function bLb(){this.c.X.style[Hxc]=(Jv(),bvc)};_.vc=function cLb(a,b){UKb(this);this.c.X.style[Hxc]=(Jv(),Jxc);this.c.W.X.style[uBc]=tBc;c5(SKb,'clientWidth:'+Zt($doc)+';clientHeight:'+Yt($doc));$()?Gq((tq(),new eLb(this)),500):ZKb(this)};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=0;_.j=null;var SKb;r3(903,1,{},eLb);_.Bb=function fLb(){ZKb(this.b);return false};_.b=null;r3(904,905,buc,xLb);_.ch=function yLb(a){wLb(this,rI(a,154))};_.dh=function zLb(){return I2b(new K2b(this.b.e),this.e)};_.b=null;_.c=0;_.d=false;_.e=null;r3(906,1,Usc,BLb);_.sb=function CLb(a){Sib(a.type)==1&&$5(this.b.b.g,Woc(Xoc(rI(this.b.b.f.Ve(),202),LW.i),iI(d2,btc,121,[this.c.Qf()])))};_.b=null;_.c=null;r3(907,905,buc,FLb);_.ch=function GLb(a){ELb(this,rI(a,191))};_.dh=function HLb(){return w1b(this.c,7)};_.b=null;_.c=null;r3(908,1,{},JLb);_.Bb=function KLb(){var a;if(!this.c.b.S){return false}YKb(this.c.b,(a=this.b,this.b=N2(this.b,quc),a));return true};_.b=suc;_.c=null;r3(909,1,{33:1,46:1},MLb);_.b=7000;_.c=null;r3(910,1,{},QLb);_.b=null;_.c=null;_.d=null;var RLb=null,SLb=null;r3(912,1,{},VLb);_.fb=function WLb(){return ULb(this)};_.b=false;r3(913,1,{},ZLb);_.fb=function $Lb(){return YLb(this)};_.b=false;r3(1315,1,Zuc);_.Qc=function dmc(){this.c.Lc(_jc(this.b.b))};var zV=k8b(uAc,'BookFlip$1',903,b$),BV=k8b(uAc,'BookFlip$2',904,y1),AV=k8b(uAc,'BookFlip$2$1',906,b$),EV=k8b(uAc,'BookFlip$3',907,y1),CV=k8b(uAc,'BookFlip$3$1',908,b$),DV=k8b(uAc,'BookFlip$3$2',909,b$),FV=k8b(uAc,'BookFlip_BinderImpl$Widgets',910,b$),wN=k8b(pDc,'DragDropEventBase',413,uN),xN=k8b(pDc,'DragStartEvent',414,wN),GV=k8b(uAc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',912,b$),HV=k8b(uAc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$2',913,b$),ZO=k8b(qDc,'AbstractModernizrTest',514,b$),$O=k8b(qDc,'CssTransforms3d',515,ZO);_uc(Dp)(13);