function EMb(){}
function IMb(){}
function d6(){_5()}
function J5(a,b){p5(a.b,b)}
function OLb(a){this.b=a}
function rMb(a){this.c=a}
function uMb(a){this.c=a}
function jMb(a,b){this.b=a;this.c=b}
function nMb(a,b){XLb();this.b=a;this.c=b}
function KMb(){KMb=Btc;AMb=new EMb}
function LMb(){LMb=Btc;BMb=new IMb}
function V5(){V5=Btc;U5=new BDb}
function c6(){c6=Btc;_5();W5(new d6)}
function W5(a){V5();U5.Ef(AP,a)}
function X5(a){V5();return a6(QI(U5.Df(a),65))}
function Djc(a,b,c,d){return new ILb(a,b,c,d)}
function p5(a,b){x5(a,(Bic(),tic),b,null)}
function BLb(){BLb=Btc;ALb=(H5(),u5(jW.i))}
function yMb(){var a;a=(LMb(),BMb);HMb(a);return a}
function HLb(a){var b;b=new q2b(a.e);ZLb(aMb(new nMb(a,b),'issue.all'))}
function FLb(a,b,c,d){ZLb(cMb(new fMb(a,b,c,d),b.Sf(),eZ.i))}
function fMb(a,b,c,d){XLb();this.b=a;this.e=b;this.c=c;this.d=d}
function zMb(a){var b;this.d=a;b=(KMb(),AMb);DMb(b);yMb();this.b=iu($doc);this.c=new T9(this.b)}
function MMb(a){var b;b=new tbc;b.b.b+=gwc;rbc(b,Z7(a));b.b.b+=hwc;return new E7(b.b.b)}
function NMb(a,b){var c;c=new tbc;c.b.b+=yDc;rbc(c,Z7(a.b));c.b.b+="\" width='100%' ><div>";rbc(c,Z7(b));c.b.b+=JCc;return new E7(c.b.b)}
function ELb(a){var b,c;for(b=0;b<7;++b){c=DLb(x3(b),a.i);FLb(a,QI(a.j.Ke(c),154),b,false)}}
function CLb(a){var b;b=ku($doc);ku($doc)>=1024?gb(a.c,Zvc+b*0.33*2+pwc):gb(a.c,Zvc+b*0.33*2+pwc)}
function mMb(a,b){a.b.j=b;a.b.i==0&&(a.b.i=a.b.j.Se());ELb(a.b);Sq((Fq(),new rMb(a)),5000);ub(a.b.b,new uMb(a),(CB(),CB(),BB))}
function DLb(a,b){return z3(a,ruc)?M3(C3(a,x3(b))):M3(A3(C3(s3(a,x3(b)),x3(b)),ruc)?E3(C3(s3(a,x3(b)),x3(b))):C3(s3(a,x3(b)),x3(b)))}
function _5(){_5=Btc;Z5=$doc.createElement(OEc);$5=new BDb;$5.Ef(PEc,QEc);$5.Ef(ayc,QEc);$5.Ef('submit',REc);$5.Ef('reset',REc);$5.Ef(oyc,SEc);$5.Ef(hyc,SEc);$5.Ef('abort',SEc)}
function eMb(a,b){var c,d;d=NMb((BLb(),c8(),new _7(rDc+b.zh().c+sDc+b.xh())),a.e.jh());c=zt(a.b.b.X,a.c*2);Mt(c,d.b);a.d?Kt(c,QI(a.b.d.Df(M9b(3)),1)):Kt(c,QI(a.b.d.Df(M9b(a.c-3)),1));Pjb(c,1);Cjb(c,new jMb(a,a.e));CLb(a.b)}
function Tkc(a){!a.w&&(a.w=Djc((!a.P&&(a.P=(!a.O&&(a.O=fkc(new FPb,(!a.r&&(a.r=new BD),a.r),(!a.v&&(a.v=(!a.Y&&(a.Y=Lkc(a)),a.Y)),a.v))),a.O)),a.P),new koc(a),(!a._&&(a._=Okc(a)),a._),(!a.n&&(a.n=qlc(new lqc,(!a.r&&(a.r=new BD),a.r))),a.n)));return a.w}
function xMb(a){var b,c,d,e;c=new Ulb(MMb(a.b).b);b=V9(c.X);S9(a.c);b.c?At(b.c,b.b,b.d):Y9(b.b);Rlb(c,(d=new Ulb((e=new tbc,e.b.b+='<div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div>',new E7(e.b.b)).b),hb(d,Zvc+(yMb(),'GCL1VBJDIN')+Zvc),a.d.b=d,d),S9(a.c));a.d.c=c;return c}
function a6(a){var b,c,d,e,f;!a.b&&(a.b=(y8b(),(b=(_5(),Z5).style['perspectiveProperty']!==undefined||Z5.style['WebkitPerspective']!==undefined,b&&(b=(c=$doc.createElement(sxc),d=$doc.createElement(awc),c['textContent']='@media (-webkit-transform-3d),(modernizr){#modernizr{height:3px}}',e=$doc.getElementsByTagName(txc)[0],e.appendChild(c),d.id=OEc,yt($doc.documentElement,d),f=(d.offsetHeight||0)==3,Dt(c),Dt(d),f)),b)?x8b:w8b));return a.b.b}
function GLb(a,b){var c,d,e,f;f=DLb(K3(s3(b,jvc),kvc),a.i);d=z3(K3(b,kvc),ruc)?M3(C3(K3(b,kvc),jvc)):M3(A3(C3(s3(K3(b,kvc),jvc),jvc),ruc)?E3(C3(s3(K3(b,kvc),jvc),jvc)):C3(s3(K3(b,kvc),jvc),jvc));for(e=0;e<7;++e){c=z3(s3(K3(jvc,C3(b,jvc)),x3(e)),ruc)?M3(C3(s3(K3(jvc,C3(b,jvc)),x3(e)),jvc)):M3(A3(C3(s3(s3(K3(jvc,C3(b,jvc)),x3(e)),jvc),jvc),ruc)?E3(C3(s3(s3(K3(jvc,C3(b,jvc)),x3(e)),jvc),jvc)):C3(s3(s3(K3(jvc,C3(b,jvc)),x3(e)),jvc),jvc));Kt(zt(a.b.X,e*2),QI(a.d.Df(M9b(c-3)),1))}FLb(a,QI(a.j.Ke(f),154),d,true)}
function ILb(a,b,c,d){BLb();var e;hc.call(this);this.e=a;this.f=b;this.g=d;Ej(fc(this),'\u6700\u70ED\u95E8');e=new dc;db(e,(Be(),Ie(),GCc));ac(e,new Olb(HCc));ac(e,new Llb('1.1 3D\u7279\u6548\u7684\u521D\u6B65\u5B9E\u73B0'));ac(e,new Olb(Hwc));ac(e,new Olb(ICc));ac(e,new Llb('1.2 \u624B\u52BF\u6EDA\u52A8\uFF08\u4E2D\uFF09'));ac(e,new Llb('1.3 \u5B8C\u55843D\u7279\u6548\uFF08\u4E2D\uFF09'));Rb(this,e,this.X);gc(this,xMb(new zMb(this)));this.d=new BDb;this.d.Ef(M9b(0),'GCL1VBJDAN');this.d.Ef(M9b(1),'GCL1VBJDBN');this.d.Ef(M9b(2),'GCL1VBJDCN');this.d.Ef(M9b(3),'GCL1VBJDDN');this.d.Ef(M9b(-1),'GCL1VBJDEN');this.d.Ef(M9b(-2),'GCL1VBJDFN');this.d.Ef(M9b(-3),'GCL1VBJDGN')}
function HMb(a){if(!a.b){a.b=true;$y('.GCL1VBJDHN{background:black;}.GCL1VBJDIN{position:relative;width:100%;-webkit-transform-style:preserve-3d;height:200px;display:-webkit-box;-webkit-perspective:700;}.GCL1VBJDIN>div>img{-webkit-border-radius:10px 10px;}'+(V5(),X5((c6(),AP))?'.GCL1VBJDIN>div>img{-webkit-box-reflect:below 25px -webkit-gradient(linear,left top,left bottom,from(transparent),color-stop(0.8,transparent),to(rgba(255,255,255,0.7)));}':'.GCL1VBJDIN>div>img{-webkit-box-reflect:below 25px;}')+'.GCL1VBJDIN>div{height:1350px;position:absolute;-webkit-transition:all 0.5s ease-out;cursor:pointer;width:33%;}.GCL1VBJDIN>div>div{display:-webkit-box;-webkit-box-align:center;-webkit-box-pack:center;visibility:hidden;border:1px solid hsl(212,58%,58%);-webkit-border-radius:20px;width:100%;color:white;}');return true}return false}
function DMb(a){if(!a.b){a.b=true;$y((BG(),'.GCL1VBJDGN{-webkit-opacity:0;left:-10%;}'+(V5(),X5((c6(),AP))?'.GCL1VBJDGN{-webkit-transform:rotateY(55deg) translate(0,50px);}':'.GCL1VBJDGN{-webkit-transform:translate(0,50px);}')+'.GCL1VBJDFN{-webkit-opacity:0.5;left:1%;z-index:0;}'+(X5(AP)?'.GCL1VBJDFN{-webkit-transform:rotateY(55deg) translate(0,55px);}':'.GCL1VBJDFN{-webkit-transform:translate(0,55px);}')+'.GCL1VBJDEN{left:10%;z-index:3;}'+(X5(AP)?'.GCL1VBJDEN{-webkit-transform:rotateY(55deg) translate(20px,25px);}':'.GCL1VBJDEN{-webkit-transform:translate(20px,25px);}')+'.GCL1VBJDAN{left:34%;z-index:10;}'+(X5(AP)?'.GCL1VBJDAN{-webkit-transform:rotateY(0) scale(1.05) translate(0,30px);}':'.GCL1VBJDAN{-webkit-transform:translate(0,30px);}')+'.GCL1VBJDAN>div{visibility:visible !important;}.GCL1VBJDBN{left:58%;-index:3;}'+(X5(AP)?'.GCL1VBJDBN{-webkit-transform:rotateY(-55deg) translate(-20px,25px);}':'.GCL1VBJDBN{-webkit-transform:translate(-20px,25px);}')+'.GCL1VBJDCN{-webkit-opacity:0.5;left:67%;z-index:0;}'+(X5(AP)?'.GCL1VBJDCN{-webkit-transform:rotateY(-55deg) translate(0,55px);}':'.GCL1VBJDCN{-webkit-transform:translate(0,55px);}')+'.GCL1VBJDDN{-webkit-opacity:0;left:78%;}'+(X5(AP)?'.GCL1VBJDDN{-webkit-transform:rotateY(-55deg) translate(0,50px);}':'.GCL1VBJDDN{-webkit-transform:translate(0,50px);}')+Zvc));return true}return false}
var TEc='com.google.gwt.modernizr.client.tests.',REc='form',OEc='modernizr';var U5;Y3(523,1,wuc);_.b=null;var Z5,$5=null;Y3(524,523,wuc,d6);Y3(912,4,lvc,ILb);_.rc=function JLb(){return null};_.sc=function KLb(){};_.tc=function LLb(){this.c.X.style[Cyc]=(Wv(),$vc)};_.uc=function MLb(a,b){CLb(this);this.c.X.style[Cyc]=(Wv(),Eyc);this.c.W.X.style[CEc]=BEc;J5(ALb,'clientWidth:'+ku($doc)+';clientHeight:'+ju($doc));Nl()?Sq((Fq(),new OLb(this)),500):HLb(this)};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=0;_.j=null;var ALb;Y3(913,1,{},OLb);_.Qc=function PLb(){HLb(this.b);return false};_.b=null;Y3(914,915,Xuc,fMb);_.eh=function gMb(a){eMb(this,QI(a,157))};_.fh=function hMb(){return z3b(new B3b(this.b.e),this.e)};_.b=null;_.c=0;_.d=false;_.e=null;Y3(916,1,Jtc,jMb);_.nb=function kMb(a){Ajb(a.type)==1&&F6(this.b.b.g,Qpc(Rpc(QI(this.b.b.f.Xe(),205),tX.i),HI(K2,Xtc,124,[this.c.Sf()])))};_.b=null;_.c=null;Y3(917,915,Xuc,nMb);_.eh=function oMb(a){mMb(this,QI(a,194))};_.fh=function pMb(){return n2b(this.c,7)};_.b=null;_.c=null;Y3(918,1,{},rMb);_.Qc=function sMb(){var a;if(!this.c.b.S){return false}GLb(this.c.b,(a=this.b,this.b=s3(this.b,kvc),a));return true};_.b=mvc;_.c=null;Y3(919,1,nvc,uMb);_.nd=function vMb(a){(a.b.clientX||0)<~~(ku($doc)/2)?GLb(this.c.b,x3(++this.b)):GLb(this.c.b,x3(--this.b));(this.b>20000||this.b<0)&&(this.b=7001)};_.b=7000;_.c=null;Y3(920,1,{},zMb);_.b=null;_.c=null;_.d=null;var AMb=null,BMb=null;Y3(922,1,{},EMb);_.ub=function FMb(){return DMb(this)};_.b=false;Y3(923,1,{},IMb);_.ub=function JMb(){return HMb(this)};_.b=false;Y3(1344,1,Uvc);_.Pc=function Ync(){Apc(this.c,Tkc(this.b.b))};var aW=a9b(nBc,'BookFlip$1',913,H$),cW=a9b(nBc,'BookFlip$2',914,d2),bW=a9b(nBc,'BookFlip$2$1',916,H$),fW=a9b(nBc,'BookFlip$3',917,d2),dW=a9b(nBc,'BookFlip$3$1',918,H$),eW=a9b(nBc,'BookFlip$3$2',919,H$),gW=a9b(nBc,'BookFlip_BinderImpl$Widgets',920,H$),hW=a9b(nBc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',922,H$),iW=a9b(nBc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$2',923,H$),zP=a9b(TEc,'AbstractModernizrTest',523,H$),AP=a9b(TEc,'CssTransforms3d',524,zP);Wvc(Pp)(21);