function Aj(){}
function pj(a){this.b=a}
function sj(a){this.b=a}
function vj(a){this.b=a}
function Cj(){Cj=Ctc;xj=new Aj}
function Skc(a){!a.d&&(a.d=new nj);return a.d}
function lj(){lj=Ctc;kj=(I5(),v5(lK.i));M5(kj,cwc);zj((Cj(),xj));M5(kj,dwc)}
function zj(a){if(!a.b){a.b=true;Zy();rp(Wy,'.GCL1VBJDCB{position:absolute;top:0;bottom:0;height:100%;width:0;background-color:white;}');bz();return true}return false}
function mj(a){var b,c,d;c=new ibc;for(b=0;b<a.length;++b){d=a[b];gbc(c,'{touch-id:'+d.identifier);gbc(c,';touch-pageX:'+d.pageX);gbc(c,';touch-pageY:'+d.pageY);gbc(c,';touch-clientX:'+d.clientX);gbc(c,';touch-clientY:'+d.clientY);gbc(c,';touch-screenX:'+d.screenX);gbc(c,';touch-screenY:'+d.screenY);c.b.b+=Hxc}N5(kj,c.b.b)}
function nj(){lj();var a,b;hc.call(this);a=new Vlb('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla at turpis eget nibh ultricies dignissim. Duis luctus euismod turpis. Mauris augue. Aliquam facilisis semper elit. Pellentesque semper hendrerit arcu. Phasellus eleifend commodo justo. Aliquam orci urna, imperdiet sit amet, posuere in, lobortis et, risus. Integer interdum nonummy erat. Nullam tellus. Sed accumsan. Vestibulum orci ipsum, eleifend vitae, mollis vel, mollis sed, purus. Suspendisse mollis elit eu magna. Morbi egestas. Nunc leo ipsum, blandit ac, viverra quis, porttitor quis, dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus scelerisque ipsum ut justo. Pellentesque et ligula eu massa sagittis rutrum. In urna nibh, eleifend vel, suscipit ut, sagittis id, nunc.Nam ut sapien sed pede pulvinar rutrum. Nunc eu elit sed augue aliquet tincidunt. Morbi rutrum. Vestibulum dui turpis, lobortis quis, euismod sed, consectetuer sit amet, nunc. Nam mi. Fusce at nisl eu tortor bibendum eleifend. Sed ac metus. Phasellus nec elit. Morbi tortor nulla, tristique a, adipiscing at, consectetuer et, nisi. Nunc vel sapien sed risus hendrerit egestas. Vivamus turpis arcu, placerat eu, congue vel, commodo ut, nisl.&lt;');a.X.style[FCc]='100px';a.X.style[awc]=rCc;a.X.style[Zvc]='700px';b=new Vlb($vc);db(b,(Cj(),'GCL1VBJDCB'));Rb(a,b,a.X);gc(this,a);ub(a,new pj(this),(CC(),CC(),BC));ub(a,new sj(this),(wC(),wC(),vC));ub(a,new vj(this),(oC(),oC(),nC))}
Z3(137,4,Htc,nj);_.b=false;_.c=false;_.d=0;_.e=0;var kj;Z3(138,1,Ntc,pj);_.jc=function qj(a){var b;b=a.b.touches;switch(b.length){case 1:N5((lj(),kj),GCc);this.b.c=false;break;case 2:N5((lj(),kj),HCc);this.b.c=false;}};_.b=null;Z3(139,1,Otc,sj);_.kc=function tj(a){var b,c,d,e,f,g,i;a.b.preventDefault();i=a.b.touches;switch(i.length){case 1:if(this.b.b){return}this.b.b=true;mj(i);break;case 2:if(this.b.c){return}this.b.c=true;f=i[0];g=i[1];b=f.pageX;c=g.pageX;d=b-this.b.d;e=c-this.b.e;if(d>0&&e>0){return}else if(d<0&&e<0){return}mj(i);}};_.b=null;Z3(140,1,Ptc,vj);_.lc=function wj(a){this.b.b=false;this.b.c=false};_.b=null;var xj=null;Z3(142,1,{},Aj);_.ub=function Bj(){return zj(this)};_.b=false;Z3(1315,1,Vvc);_.Pc=function fmc(){Bpc(this.c,Skc(this.b.b))};var hK=b9b(eBc,'WaveTest$1',138,I$),iK=b9b(eBc,'WaveTest$2',139,I$),jK=b9b(eBc,'WaveTest$3',140,I$),kK=b9b(eBc,'WaveTest_Bundle_zh_InlineClientBundleGenerator$1',142,I$);Xvc(Qp)(8);