function FMb(){}
function JMb(){}
function e6(){a6()}
function PLb(a){this.b=a}
function sMb(a){this.c=a}
function vMb(a){this.c=a}
function K5(a,b){q5(a.b,b)}
function X5(a){W5();V5.Ef(BP,a)}
function W5(){W5=Ctc;V5=new CDb}
function LMb(){LMb=Ctc;BMb=new FMb}
function MMb(){MMb=Ctc;CMb=new JMb}
function d6(){d6=Ctc;a6();X5(new e6)}
function CLb(){CLb=Ctc;BLb=(I5(),v5(kW.i))}
function kMb(a,b){this.b=a;this.c=b}
function oMb(a,b){YLb();this.b=a;this.c=b}
function gMb(a,b,c,d){YLb();this.b=a;this.e=b;this.c=c;this.d=d}
function GLb(a,b,c,d){$Lb(dMb(new gMb(a,b,c,d),b.Sf(),fZ.i))}
function Ejc(a,b,c,d){return new JLb(a,b,c,d)}
function Y5(a){W5();return b6(RI(V5.Df(a),65))}
function q5(a,b){y5(a,(Cic(),uic),b,null)}
function zMb(){var a;a=(MMb(),CMb);IMb(a);return a}
function ILb(a){var b;b=new r2b(a.e);$Lb(bMb(new oMb(a,b),'issue.all'))}
function NMb(a){var b;b=new ubc;b.b.b+=hwc;sbc(b,$7(a));b.b.b+=iwc;return new F7(b.b.b)}
function AMb(a){var b;this.d=a;b=(LMb(),BMb);EMb(b);zMb();this.b=ju($doc);this.c=new U9(this.b)}
function FLb(a){var b,c;for(b=0;b<7;++b){c=ELb(y3(b),a.i);GLb(a,RI(a.j.Ke(c),154),b,false)}}
function DLb(a){var b;b=lu($doc);lu($doc)>=1024?gb(a.c,$vc+b*0.33*2+qwc):gb(a.c,$vc+b*0.33*2+qwc)}
function nMb(a,b){a.b.j=b;a.b.i==0&&(a.b.i=a.b.j.Se());FLb(a.b);Tq((Gq(),new sMb(a)),5000);ub(a.b.b,new vMb(a),(DB(),DB(),CB))}
function ELb(a,b){return A3(a,suc)?N3(D3(a,y3(b))):N3(B3(D3(t3(a,y3(b)),y3(b)),suc)?F3(D3(t3(a,y3(b)),y3(b))):D3(t3(a,y3(b)),y3(b)))}
function OMb(a,b){var c;c=new ubc;c.b.b+=iEc;sbc(c,$7(a.b));c.b.b+="\" width='100%' ><div>";sbc(c,$7(b));c.b.b+=nCc;return new F7(c.b.b)}
function a6(){a6=Ctc;$5=$doc.createElement(bEc);_5=new CDb;_5.Ef(cEc,dEc);_5.Ef(byc,dEc);_5.Ef('submit',eEc);_5.Ef('reset',eEc);_5.Ef(pyc,fEc);_5.Ef(iyc,fEc);_5.Ef('abort',fEc)}
function fMb(a,b){var c,d;d=OMb((CLb(),d8(),new a8(gEc+b.zh().c+hEc+b.xh())),a.e.jh());c=At(a.b.b.X,a.c*2);Nt(c,d.b);a.d?Lt(c,RI(a.b.d.Df(N9b(3)),1)):Lt(c,RI(a.b.d.Df(N9b(a.c-3)),1));Qjb(c,1);Djb(c,new kMb(a,a.e));DLb(a.b)}
function Ukc(a){!a.w&&(a.w=Ejc((!a.P&&(a.P=(!a.O&&(a.O=gkc(new GPb,(!a.r&&(a.r=new CD),a.r),(!a.v&&(a.v=(!a.Y&&(a.Y=Mkc(a)),a.Y)),a.v))),a.O)),a.P),new Nlc(a),(!a._&&(a._=Pkc(a)),a._),(!a.n&&(a.n=rlc(new mqc,(!a.r&&(a.r=new CD),a.r))),a.n)));return a.w}
function yMb(a){var b,c,d,e;c=new Vlb(NMb(a.b).b);b=W9(c.X);T9(a.c);b.c?Bt(b.c,b.b,b.d):Z9(b.b);Slb(c,(d=new Vlb((e=new ubc,e.b.b+='<div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div>',new F7(e.b.b)).b),hb(d,$vc+(zMb(),'GCL1VBJDLN')+$vc),a.d.b=d,d),T9(a.c));a.d.c=c;return c}
function b6(a){var b,c,d,e,f;!a.b&&(a.b=(z8b(),(b=(a6(),$5).style['perspectiveProperty']!==undefined||$5.style['WebkitPerspective']!==undefined,b&&(b=(c=$doc.createElement(txc),d=$doc.createElement(bwc),c['textContent']='@media (-webkit-transform-3d),(modernizr){#modernizr{height:3px}}',e=$doc.getElementsByTagName(uxc)[0],e.appendChild(c),d.id=bEc,zt($doc.documentElement,d),f=(d.offsetHeight||0)==3,Et(c),Et(d),f)),b)?y8b:x8b));return a.b.b}
function HLb(a,b){var c,d,e,f;f=ELb(L3(t3(b,kvc),lvc),a.i);d=A3(L3(b,lvc),suc)?N3(D3(L3(b,lvc),kvc)):N3(B3(D3(t3(L3(b,lvc),kvc),kvc),suc)?F3(D3(t3(L3(b,lvc),kvc),kvc)):D3(t3(L3(b,lvc),kvc),kvc));for(e=0;e<7;++e){c=A3(t3(L3(kvc,D3(b,kvc)),y3(e)),suc)?N3(D3(t3(L3(kvc,D3(b,kvc)),y3(e)),kvc)):N3(B3(D3(t3(t3(L3(kvc,D3(b,kvc)),y3(e)),kvc),kvc),suc)?F3(D3(t3(t3(L3(kvc,D3(b,kvc)),y3(e)),kvc),kvc)):D3(t3(t3(L3(kvc,D3(b,kvc)),y3(e)),kvc),kvc));Lt(At(a.b.X,e*2),RI(a.d.Df(N9b(c-3)),1))}GLb(a,RI(a.j.Ke(f),154),d,true)}
function JLb(a,b,c,d){CLb();var e;hc.call(this);this.e=a;this.f=b;this.g=d;Fj(fc(this),'\u6700\u70ED\u95E8');e=new dc;db(e,(Ce(),Je(),OCc));ac(e,new Plb(PCc));ac(e,new Mlb('1.1 3D\u7279\u6548\u7684\u521D\u6B65\u5B9E\u73B0'));ac(e,new Plb(Iwc));ac(e,new Plb(QCc));ac(e,new Mlb('1.2 \u624B\u52BF\u6EDA\u52A8\uFF08\u4E2D\uFF09'));ac(e,new Mlb('1.3 \u5B8C\u55843D\u7279\u6548\uFF08\u4E2D\uFF09'));Rb(this,e,this.X);gc(this,yMb(new AMb(this)));this.d=new CDb;this.d.Ef(N9b(0),'GCL1VBJDDN');this.d.Ef(N9b(1),'GCL1VBJDEN');this.d.Ef(N9b(2),'GCL1VBJDFN');this.d.Ef(N9b(3),'GCL1VBJDGN');this.d.Ef(N9b(-1),'GCL1VBJDHN');this.d.Ef(N9b(-2),'GCL1VBJDIN');this.d.Ef(N9b(-3),'GCL1VBJDJN')}
function IMb(a){if(!a.b){a.b=true;_y('.GCL1VBJDKN{background:black;}.GCL1VBJDLN{position:relative;width:100%;-webkit-transform-style:preserve-3d;height:200px;display:-webkit-box;-webkit-perspective:700;}.GCL1VBJDLN>div>img{-webkit-border-radius:10px 10px;}'+(W5(),Y5((d6(),BP))?'.GCL1VBJDLN>div>img{-webkit-box-reflect:below 25px -webkit-gradient(linear,left top,left bottom,from(transparent),color-stop(0.8,transparent),to(rgba(255,255,255,0.7)));}':'.GCL1VBJDLN>div>img{-webkit-box-reflect:below 25px;}')+'.GCL1VBJDLN>div{height:1350px;position:absolute;-webkit-transition:all 0.5s ease-out;cursor:pointer;width:33%;}.GCL1VBJDLN>div>div{display:-webkit-box;-webkit-box-align:center;-webkit-box-pack:center;visibility:hidden;border:1px solid hsl(212,58%,58%);-webkit-border-radius:20px;width:100%;color:white;}');return true}return false}
function EMb(a){if(!a.b){a.b=true;_y((CG(),'.GCL1VBJDJN{-webkit-opacity:0;left:-10%;}'+(W5(),Y5((d6(),BP))?'.GCL1VBJDJN{-webkit-transform:rotateY(55deg) translate(0,50px);}':'.GCL1VBJDJN{-webkit-transform:translate(0,50px);}')+'.GCL1VBJDIN{-webkit-opacity:0.5;left:1%;z-index:0;}'+(Y5(BP)?'.GCL1VBJDIN{-webkit-transform:rotateY(55deg) translate(0,55px);}':'.GCL1VBJDIN{-webkit-transform:translate(0,55px);}')+'.GCL1VBJDHN{left:10%;z-index:3;}'+(Y5(BP)?'.GCL1VBJDHN{-webkit-transform:rotateY(55deg) translate(20px,25px);}':'.GCL1VBJDHN{-webkit-transform:translate(20px,25px);}')+'.GCL1VBJDDN{left:34%;z-index:10;}'+(Y5(BP)?'.GCL1VBJDDN{-webkit-transform:rotateY(0) scale(1.05) translate(0,30px);}':'.GCL1VBJDDN{-webkit-transform:translate(0,30px);}')+'.GCL1VBJDDN>div{visibility:visible !important;}.GCL1VBJDEN{left:58%;-index:3;}'+(Y5(BP)?'.GCL1VBJDEN{-webkit-transform:rotateY(-55deg) translate(-20px,25px);}':'.GCL1VBJDEN{-webkit-transform:translate(-20px,25px);}')+'.GCL1VBJDFN{-webkit-opacity:0.5;left:67%;z-index:0;}'+(Y5(BP)?'.GCL1VBJDFN{-webkit-transform:rotateY(-55deg) translate(0,55px);}':'.GCL1VBJDFN{-webkit-transform:translate(0,55px);}')+'.GCL1VBJDGN{-webkit-opacity:0;left:78%;}'+(Y5(BP)?'.GCL1VBJDGN{-webkit-transform:rotateY(-55deg) translate(0,50px);}':'.GCL1VBJDGN{-webkit-transform:translate(0,50px);}')+$vc));return true}return false}
var jEc='com.google.gwt.modernizr.client.tests.',eEc='form',bEc='modernizr';var V5;Z3(523,1,xuc);_.b=null;var $5,_5=null;Z3(524,523,xuc,e6);Z3(912,4,mvc,JLb);_.rc=function KLb(){return null};_.sc=function LLb(){};_.tc=function MLb(){this.c.X.style[Dyc]=(Xv(),_vc)};_.uc=function NLb(a,b){DLb(this);this.c.X.style[Dyc]=(Xv(),Fyc);this.c.W.X.style[MDc]=LDc;K5(BLb,'clientWidth:'+lu($doc)+';clientHeight:'+ku($doc));Ol()?Tq((Gq(),new PLb(this)),500):ILb(this)};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=0;_.j=null;var BLb;Z3(913,1,{},PLb);_.Qc=function QLb(){ILb(this.b);return false};_.b=null;Z3(914,915,Yuc,gMb);_.eh=function hMb(a){fMb(this,RI(a,157))};_.fh=function iMb(){return A3b(new C3b(this.b.e),this.e)};_.b=null;_.c=0;_.d=false;_.e=null;Z3(916,1,Ktc,kMb);_.nb=function lMb(a){Bjb(a.type)==1&&G6(this.b.b.g,Rpc(Spc(RI(this.b.b.f.Xe(),205),uX.i),II(L2,Ytc,124,[this.c.Sf()])))};_.b=null;_.c=null;Z3(917,915,Yuc,oMb);_.eh=function pMb(a){nMb(this,RI(a,194))};_.fh=function qMb(){return o2b(this.c,7)};_.b=null;_.c=null;Z3(918,1,{},sMb);_.Qc=function tMb(){var a;if(!this.c.b.S){return false}HLb(this.c.b,(a=this.b,this.b=t3(this.b,lvc),a));return true};_.b=nvc;_.c=null;Z3(919,1,ovc,vMb);_.nd=function wMb(a){(a.b.clientX||0)<~~(lu($doc)/2)?HLb(this.c.b,y3(++this.b)):HLb(this.c.b,y3(--this.b));(this.b>20000||this.b<0)&&(this.b=7001)};_.b=7000;_.c=null;Z3(920,1,{},AMb);_.b=null;_.c=null;_.d=null;var BMb=null,CMb=null;Z3(922,1,{},FMb);_.ub=function GMb(){return EMb(this)};_.b=false;Z3(923,1,{},JMb);_.ub=function KMb(){return IMb(this)};_.b=false;Z3(1317,1,Vvc);_.Pc=function mmc(){Bpc(this.c,Ukc(this.b.b))};var bW=b9b(fBc,'BookFlip$1',913,I$),dW=b9b(fBc,'BookFlip$2',914,e2),cW=b9b(fBc,'BookFlip$2$1',916,I$),gW=b9b(fBc,'BookFlip$3',917,e2),eW=b9b(fBc,'BookFlip$3$1',918,I$),fW=b9b(fBc,'BookFlip$3$2',919,I$),hW=b9b(fBc,'BookFlip_BinderImpl$Widgets',920,I$),iW=b9b(fBc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',922,I$),jW=b9b(fBc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$2',923,I$),AP=b9b(jEc,'AbstractModernizrTest',523,I$),BP=b9b(jEc,'CssTransforms3d',524,AP);Xvc(Qp)(9);