function HMb(){}
function LMb(){}
function g6(){c6()}
function RLb(a){this.b=a}
function uMb(a){this.c=a}
function xMb(a){this.c=a}
function M5(a,b){s5(a.b,b)}
function Z5(a){Y5();X5.Ef(CP,a)}
function Y5(){Y5=Mtc;X5=new EDb}
function NMb(){NMb=Mtc;DMb=new HMb}
function OMb(){OMb=Mtc;EMb=new LMb}
function f6(){f6=Mtc;c6();Z5(new g6)}
function ELb(){ELb=Mtc;DLb=(K5(),x5(lW.i))}
function mMb(a,b){this.b=a;this.c=b}
function qMb(a,b){$Lb();this.b=a;this.c=b}
function iMb(a,b,c,d){$Lb();this.b=a;this.e=b;this.c=c;this.d=d}
function ILb(a,b,c,d){aMb(fMb(new iMb(a,b,c,d),b.Sf(),hZ.i))}
function Ojc(a,b,c,d){return new LLb(a,b,c,d)}
function $5(a){Y5();return d6(SI(X5.Df(a),65))}
function s5(a,b){A5(a,(Mic(),Eic),b,null)}
function BMb(){var a;a=(OMb(),EMb);KMb(a);return a}
function KLb(a){var b;b=new A2b(a.e);aMb(dMb(new qMb(a,b),'issue.all'))}
function PMb(a){var b;b=new Ebc;b.b.b+=rwc;Cbc(b,a8(a));b.b.b+=swc;return new H7(b.b.b)}
function CMb(a){var b;this.d=a;b=(NMb(),DMb);GMb(b);BMb();this.b=ku($doc);this.c=new W9(this.b)}
function HLb(a){var b,c;for(b=0;b<7;++b){c=GLb(A3(b),a.i);ILb(a,SI(a.j.Ke(c),155),b,false)}}
function FLb(a){var b;b=mu($doc);mu($doc)>=1024?hb(a.c,iwc+b*0.33*2+Awc):hb(a.c,iwc+b*0.33*2+Awc)}
function pMb(a,b){a.b.j=b;a.b.i==0&&(a.b.i=a.b.j.Se());HLb(a.b);Uq((Hq(),new uMb(a)),5000);vb(a.b.b,new xMb(a),(EB(),EB(),DB))}
function GLb(a,b){return C3(a,Cuc)?P3(F3(a,A3(b))):P3(D3(F3(v3(a,A3(b)),A3(b)),Cuc)?H3(F3(v3(a,A3(b)),A3(b))):F3(v3(a,A3(b)),A3(b)))}
function QMb(a,b){var c;c=new Ebc;c.b.b+=_Dc;Cbc(c,a8(a.b));c.b.b+="\" width='100%' ><div>";Cbc(c,a8(b));c.b.b+=wCc;return new H7(c.b.b)}
function c6(){c6=Mtc;a6=$doc.createElement(UDc);b6=new EDb;b6.Ef(VDc,WDc);b6.Ef(lyc,WDc);b6.Ef('submit',XDc);b6.Ef('reset',XDc);b6.Ef(zyc,YDc);b6.Ef(syc,YDc);b6.Ef('abort',YDc)}
function hMb(a,b){var c,d;d=QMb((ELb(),f8(),new c8(ZDc+b.zh().c+$Dc+b.xh())),a.e.jh());c=Bt(a.b.b.X,a.c*2);Ot(c,d.b);a.d?Mt(c,SI(a.b.d.Df(X9b(3)),1)):Mt(c,SI(a.b.d.Df(X9b(a.c-3)),1));Sjb(c,1);Fjb(c,new mMb(a,a.e));FLb(a.b)}
function blc(a){!a.w&&(a.w=Ojc((!a.P&&(a.P=(!a.O&&(a.O=qkc(new IPb,(!a.r&&(a.r=new DD),a.r),(!a.v&&(a.v=(!a.Y&&(a.Y=Vkc(a)),a.Y)),a.v))),a.O)),a.P),new Wlc(a),(!a._&&(a._=Ykc(a)),a._),(!a.n&&(a.n=Alc(new wqc,(!a.r&&(a.r=new DD),a.r))),a.n)));return a.w}
function AMb(a){var b,c,d,e;c=new Xlb(PMb(a.b).b);b=Y9(c.X);V9(a.c);b.c?Ct(b.c,b.b,b.d):_9(b.b);Ulb(c,(d=new Xlb((e=new Ebc,e.b.b+='<div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div> <div><\/div>',new H7(e.b.b)).b),ib(d,iwc+(BMb(),'GCL1VBJDCO')+iwc),a.d.b=d,d),V9(a.c));a.d.c=c;return c}
function d6(a){var b,c,d,e,f;!a.b&&(a.b=(J8b(),(b=(c6(),a6).style['perspectiveProperty']!==undefined||a6.style['WebkitPerspective']!==undefined,b&&(b=(c=$doc.createElement(Dxc),d=$doc.createElement(lwc),c['textContent']='@media (-webkit-transform-3d),(modernizr){#modernizr{height:3px}}',e=$doc.getElementsByTagName(Exc)[0],e.appendChild(c),d.id=UDc,At($doc.documentElement,d),f=(d.offsetHeight||0)==3,Ft(c),Ft(d),f)),b)?I8b:H8b));return a.b.b}
function JLb(a,b){var c,d,e,f;f=GLb(N3(v3(b,uvc),vvc),a.i);d=C3(N3(b,vvc),Cuc)?P3(F3(N3(b,vvc),uvc)):P3(D3(F3(v3(N3(b,vvc),uvc),uvc),Cuc)?H3(F3(v3(N3(b,vvc),uvc),uvc)):F3(v3(N3(b,vvc),uvc),uvc));for(e=0;e<7;++e){c=C3(v3(N3(uvc,F3(b,uvc)),A3(e)),Cuc)?P3(F3(v3(N3(uvc,F3(b,uvc)),A3(e)),uvc)):P3(D3(F3(v3(v3(N3(uvc,F3(b,uvc)),A3(e)),uvc),uvc),Cuc)?H3(F3(v3(v3(N3(uvc,F3(b,uvc)),A3(e)),uvc),uvc)):F3(v3(v3(N3(uvc,F3(b,uvc)),A3(e)),uvc),uvc));Mt(Bt(a.b.X,e*2),SI(a.d.Df(X9b(c-3)),1))}ILb(a,SI(a.j.Ke(f),155),d,true)}
function LLb(a,b,c,d){ELb();var e;ic.call(this);this.e=a;this.f=b;this.g=d;Gj(gc(this),'\u6700\u70ED\u95E8');e=new ec;db(e,(De(),Ke(),zCc));bc(e,new Rlb(ACc));bc(e,new Olb('1.1 3D\u7279\u6548\u7684\u521D\u6B65\u5B9E\u73B0'));bc(e,new Rlb(Swc));bc(e,new Rlb(BCc));bc(e,new Olb('1.2 \u624B\u52BF\u6EDA\u52A8\uFF08\u4E2D\uFF09'));bc(e,new Olb('1.3 \u5B8C\u55843D\u7279\u6548\uFF08\u4E2D\uFF09'));Sb(this,e,this.X);hc(this,AMb(new CMb(this)));this.d=new EDb;this.d.Ef(X9b(0),'GCL1VBJDKN');this.d.Ef(X9b(1),'GCL1VBJDLN');this.d.Ef(X9b(2),'GCL1VBJDMN');this.d.Ef(X9b(3),'GCL1VBJDNN');this.d.Ef(X9b(-1),'GCL1VBJDON');this.d.Ef(X9b(-2),'GCL1VBJDPN');this.d.Ef(X9b(-3),'GCL1VBJDAO')}
function KMb(a){if(!a.b){a.b=true;az('.GCL1VBJDBO{background:black;}.GCL1VBJDCO{position:relative;width:100%;-webkit-transform-style:preserve-3d;height:200px;display:-webkit-box;-webkit-perspective:700;}.GCL1VBJDCO>div>img{-webkit-border-radius:10px 10px;}'+(Y5(),$5((f6(),CP))?'.GCL1VBJDCO>div>img{-webkit-box-reflect:below 25px -webkit-gradient(linear,left top,left bottom,from(transparent),color-stop(0.8,transparent),to(rgba(255,255,255,0.7)));}':'.GCL1VBJDCO>div>img{-webkit-box-reflect:below 25px;}')+'.GCL1VBJDCO>div{height:1350px;position:absolute;-webkit-transition:all 0.5s ease-out;cursor:pointer;width:33%;}.GCL1VBJDCO>div>div{display:-webkit-box;-webkit-box-align:center;-webkit-box-pack:center;visibility:hidden;border:1px solid hsl(212,58%,58%);-webkit-border-radius:20px;width:100%;color:white;}');return true}return false}
function GMb(a){if(!a.b){a.b=true;az((DG(),'.GCL1VBJDAO{-webkit-opacity:0;left:-10%;}'+(Y5(),$5((f6(),CP))?'.GCL1VBJDAO{-webkit-transform:rotateY(55deg) translate(0,50px);}':'.GCL1VBJDAO{-webkit-transform:translate(0,50px);}')+'.GCL1VBJDPN{-webkit-opacity:0.5;left:1%;z-index:0;}'+($5(CP)?'.GCL1VBJDPN{-webkit-transform:rotateY(55deg) translate(0,55px);}':'.GCL1VBJDPN{-webkit-transform:translate(0,55px);}')+'.GCL1VBJDON{left:10%;z-index:3;}'+($5(CP)?'.GCL1VBJDON{-webkit-transform:rotateY(55deg) translate(20px,25px);}':'.GCL1VBJDON{-webkit-transform:translate(20px,25px);}')+'.GCL1VBJDKN{left:34%;z-index:10;}'+($5(CP)?'.GCL1VBJDKN{-webkit-transform:rotateY(0) scale(1.05) translate(0,30px);}':'.GCL1VBJDKN{-webkit-transform:translate(0,30px);}')+'.GCL1VBJDKN>div{visibility:visible !important;}.GCL1VBJDLN{left:58%;-index:3;}'+($5(CP)?'.GCL1VBJDLN{-webkit-transform:rotateY(-55deg) translate(-20px,25px);}':'.GCL1VBJDLN{-webkit-transform:translate(-20px,25px);}')+'.GCL1VBJDMN{-webkit-opacity:0.5;left:67%;z-index:0;}'+($5(CP)?'.GCL1VBJDMN{-webkit-transform:rotateY(-55deg) translate(0,55px);}':'.GCL1VBJDMN{-webkit-transform:translate(0,55px);}')+'.GCL1VBJDNN{-webkit-opacity:0;left:78%;}'+($5(CP)?'.GCL1VBJDNN{-webkit-transform:rotateY(-55deg) translate(0,50px);}':'.GCL1VBJDNN{-webkit-transform:translate(0,50px);}')+iwc));return true}return false}
var aEc='com.google.gwt.modernizr.client.tests.',XDc='form',UDc='modernizr';var X5;_3(523,1,Huc);_.b=null;var a6,b6=null;_3(524,523,Huc,g6);_3(912,4,wvc,LLb);_.rc=function MLb(){return null};_.sc=function NLb(){};_.tc=function OLb(){this.c.X.style[Nyc]=(Yv(),jwc)};_.uc=function PLb(a,b){FLb(this);this.c.X.style[Nyc]=(Yv(),Pyc);this.c.W.X.style[CDc]=BDc;M5(DLb,'clientWidth:'+mu($doc)+';clientHeight:'+lu($doc));Pl()?Uq((Hq(),new RLb(this)),500):KLb(this)};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=0;_.j=null;var DLb;_3(913,1,{},RLb);_.Qc=function SLb(){KLb(this.b);return false};_.b=null;_3(914,915,gvc,iMb);_.eh=function jMb(a){hMb(this,SI(a,158))};_.fh=function kMb(){return J3b(new L3b(this.b.e),this.e)};_.b=null;_.c=0;_.d=false;_.e=null;_3(916,1,Utc,mMb);_.nb=function nMb(a){Djb(a.type)==1&&I6(this.b.b.g,_pc(aqc(SI(this.b.b.f.Xe(),206),wX.i),JI(N2,guc,124,[this.c.Sf()])))};_.b=null;_.c=null;_3(917,915,gvc,qMb);_.eh=function rMb(a){pMb(this,SI(a,195))};_.fh=function sMb(){return x2b(this.c,7)};_.b=null;_.c=null;_3(918,1,{},uMb);_.Qc=function vMb(){var a;if(!this.c.b.S){return false}JLb(this.c.b,(a=this.b,this.b=v3(this.b,vvc),a));return true};_.b=xvc;_.c=null;_3(919,1,yvc,xMb);_.nd=function yMb(a){(a.b.clientX||0)<~~(mu($doc)/2)?JLb(this.c.b,A3(++this.b)):JLb(this.c.b,A3(--this.b));(this.b>20000||this.b<0)&&(this.b=7001)};_.b=7000;_.c=null;_3(920,1,{},CMb);_.b=null;_.c=null;_.d=null;var DMb=null,EMb=null;_3(922,1,{},HMb);_.ub=function IMb(){return GMb(this)};_.b=false;_3(923,1,{},LMb);_.ub=function MMb(){return KMb(this)};_.b=false;_3(1331,1,dwc);_.Pc=function lnc(){this.c.Kc(blc(this.b.b))};var cW=l9b(ABc,'BookFlip$1',913,K$),eW=l9b(ABc,'BookFlip$2',914,g2),dW=l9b(ABc,'BookFlip$2$1',916,K$),hW=l9b(ABc,'BookFlip$3',917,g2),fW=l9b(ABc,'BookFlip$3$1',918,K$),gW=l9b(ABc,'BookFlip$3$2',919,K$),iW=l9b(ABc,'BookFlip_BinderImpl$Widgets',920,K$),jW=l9b(ABc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$1',922,K$),kW=l9b(ABc,'BookFlip_BinderImpl_GenBundle_zh_InlineClientBundleGenerator$2',923,K$),BP=l9b(aEc,'AbstractModernizrTest',523,K$),CP=l9b(aEc,'CssTransforms3d',524,BP);fwc(Rp)(14);