function Bj(){}
function qj(a){this.b=a}
function tj(a){this.b=a}
function wj(a){this.b=a}
function Dj(){Dj=Mtc;yj=new Bj}
function _kc(a){!a.d&&(a.d=new oj);return a.d}
function mj(){mj=Mtc;lj=(K5(),x5(mK.i));O5(lj,mwc);Aj((Dj(),yj));O5(lj,nwc)}
function Aj(a){if(!a.b){a.b=true;$y();sp(Xy,'.GCL1VBJDCB{position:absolute;top:0;bottom:0;height:100%;width:0;background-color:white;}');cz();return true}return false}
function nj(a){var b,c,d;c=new sbc;for(b=0;b<a.length;++b){d=a[b];qbc(c,'{touch-id:'+d.identifier);qbc(c,';touch-pageX:'+d.pageX);qbc(c,';touch-pageY:'+d.pageY);qbc(c,';touch-clientX:'+d.clientX);qbc(c,';touch-clientY:'+d.clientY);qbc(c,';touch-screenX:'+d.screenX);qbc(c,';touch-screenY:'+d.screenY);c.b.b+=Rxc}P5(lj,c.b.b)}
function oj(){mj();var a,b;ic.call(this);a=new Xlb('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nulla at turpis eget nibh ultricies dignissim. Duis luctus euismod turpis. Mauris augue. Aliquam facilisis semper elit. Pellentesque semper hendrerit arcu. Phasellus eleifend commodo justo. Aliquam orci urna, imperdiet sit amet, posuere in, lobortis et, risus. Integer interdum nonummy erat. Nullam tellus. Sed accumsan. Vestibulum orci ipsum, eleifend vitae, mollis vel, mollis sed, purus. Suspendisse mollis elit eu magna. Morbi egestas. Nunc leo ipsum, blandit ac, viverra quis, porttitor quis, dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus scelerisque ipsum ut justo. Pellentesque et ligula eu massa sagittis rutrum. In urna nibh, eleifend vel, suscipit ut, sagittis id, nunc.Nam ut sapien sed pede pulvinar rutrum. Nunc eu elit sed augue aliquet tincidunt. Morbi rutrum. Vestibulum dui turpis, lobortis quis, euismod sed, consectetuer sit amet, nunc. Nam mi. Fusce at nisl eu tortor bibendum eleifend. Sed ac metus. Phasellus nec elit. Morbi tortor nulla, tristique a, adipiscing at, consectetuer et, nisi. Nunc vel sapien sed risus hendrerit egestas. Vivamus turpis arcu, placerat eu, congue vel, commodo ut, nisl.&lt;');a.X.style[_Cc]='100px';a.X.style[kwc]=aDc;a.X.style[hwc]='700px';b=new Xlb(iwc);db(b,(Dj(),'GCL1VBJDCB'));Sb(a,b,a.X);hc(this,a);vb(a,new qj(this),(DC(),DC(),CC));vb(a,new tj(this),(xC(),xC(),wC));vb(a,new wj(this),(pC(),pC(),oC))}
_3(137,4,Rtc,oj);_.b=false;_.c=false;_.d=0;_.e=0;var lj;_3(138,1,Xtc,qj);_.jc=function rj(a){var b;b=a.b.touches;switch(b.length){case 1:P5((mj(),lj),bDc);this.b.c=false;break;case 2:P5((mj(),lj),cDc);this.b.c=false;}};_.b=null;_3(139,1,Ytc,tj);_.kc=function uj(a){var b,c,d,e,f,g,i;a.b.preventDefault();i=a.b.touches;switch(i.length){case 1:if(this.b.b){return}this.b.b=true;nj(i);break;case 2:if(this.b.c){return}this.b.c=true;f=i[0];g=i[1];b=f.pageX;c=g.pageX;d=b-this.b.d;e=c-this.b.e;if(d>0&&e>0){return}else if(d<0&&e<0){return}nj(i);}};_.b=null;_3(140,1,Ztc,wj);_.lc=function xj(a){this.b.b=false;this.b.c=false};_.b=null;var yj=null;_3(142,1,{},Bj);_.ub=function Cj(){return Aj(this)};_.b=false;_3(1314,1,dwc);_.Pc=function hmc(){this.c.Kc(_kc(this.b.b))};var iK=l9b(zBc,'WaveTest$1',138,K$),jK=l9b(zBc,'WaveTest$2',139,K$),kK=l9b(zBc,'WaveTest$3',140,K$),lK=l9b(zBc,'WaveTest_Bundle_zh_InlineClientBundleGenerator$1',142,K$);fwc(Rp)(7);